const RECOMMENDATIONS = [

  // ═══════════════════════════════════════════════════
  // FLOUR DUST - HSE FL Series
  // ═══════════════════════════════════════════════════

  { id: 1,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Install LEV at the source of dust generation for all flour handling tasks, including bag opening, tipping, dough mixing, moulding, dividing, bagging, and improver handling." },
  { id: 2,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "A permanent, fixed dust extraction system is the preferred option; a stand-alone mobile dust collector is acceptable only where fixed installation is not reasonably practicable." },
  { id: 3,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Enclose the process as much as possible - use see-through panels and plastic strip curtains to reduce open areas while maintaining safe access." },
  { id: 4,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Airflow velocity must be sufficient to effectively capture airborne contaminants. Adequacy will depend on hood/enclosure design, opening size, and the specific process and substance." },
  { id: 5,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Keep extraction ductwork as short and direct as possible; avoid long runs of flexible ducting." },
  { id: 6,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Position work areas away from doors, windows, and walkways to prevent draughts from disrupting LEV performance and dispersing airborne dust." },
  { id: 7,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Discharge extracted air to a safe external location, away from doors, windows, and fresh air inlets." },
  { id: 8,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Fit airflow indicators or equivalent devices on all LEV systems to allow workers to confirm the system is operating before commencing work." },
  { id: 9,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Fit filter blockage/failure indicator alarms to all LEV and stand-alone dust collector units." },
  { id: 10, group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Confirm LEV is switched on and functioning correctly at the start of each work period - check the gauge." },
  { id: 11, group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "For stand-alone dust collectors: the unit must not release dust on start-up and should recirculate clean air; a secondary filter meeting at least dust Type M (medium hazard) classification is required for workplace recirculation." },
  { id: 12, group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Do not allow the waste bag on stand-alone units to overfill - check gauges regularly and keep sufficient spare filters and bags on site." },
  { id: 13, group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Provide a good standard of general (dilution) ventilation throughout the work area to supplement LEV." },

  { id: 14, group: "Flour", cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
    text: "Apply LEV with rim extraction at the tipping/mixing point; put a solid lid on the mixer where practicable." },
  { id: 15, group: "Flour", cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
    text: "Tip flour gently - never dump. Add ingredients gently, trickle water down the inside of the bowl, and start the mixer on slow speed." },
  { id: 16, group: "Flour", cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
    text: "When crushing empty bags, roll them up with the open end positioned within the extraction zone to capture released dust." },
  { id: 17, group: "Flour", cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
    text: "Consider providing mechanical or pneumatic bag/sack handling assistance to reduce manual handling and dust generation." },

  { id: 18, group: "Flour", cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
    text: "Use LEV cabinet extraction when weighing flour improvers." },
  { id: 19, group: "Flour", cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
    text: "Substitute high-dust improvers with low-dust alternatives wherever possible, e.g. dust-suppressed products, low-dust granules, or paste formulations." },
  { id: 20, group: "Flour", cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
    text: "Eliminate weighing entirely where practicable by using single-dose packets." },
  { id: 21, group: "Flour", cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
    text: "Open improver containers with care to minimise dust release; keep used scoops and utensils inside the extraction cabinet until cleaned." },

  { id: 22, group: "Flour", cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
    text: "Apply LEV with extraction slots at the rear of the work table; keep extraction slots free from obstructions at all times." },
  { id: 23, group: "Flour", cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
    text: "Eliminate dusting with flour wherever possible - use non-stick table surfaces or food-grade oil as a lubricant." },
  { id: 24, group: "Flour", cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
    text: "Where dusting cannot be avoided, workers should cast flour gently towards the extraction slots rather than across the open workspace." },
  { id: 25, group: "Flour", cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
    text: "Provide easy access to remove dust build-up behind extraction slots." },

  { id: 26, group: "Flour", cat: "Task",   sec: "Task-specific - Flour Bagging (FL5)",
    text: "Apply LEV enclosing the bagging point; use a filling nozzle that directs displaced air directly into the extraction system." },
  { id: 27, group: "Flour", cat: "Task",   sec: "Task-specific - Flour Bagging (FL5)",
    text: "Ensure the filling nozzle design does not spill flour when a bag is removed." },
  { id: 28, group: "Flour", cat: "Task",   sec: "Task-specific - Flour Bagging (FL5)",
    text: "Provide an extracted hopper at floor level to capture flour spills." },

  { id: 29, group: "Flour", cat: "Task",   sec: "Task-specific - Bulk Improver Addition in Flour Milling (FL6)",
    text: "Automate this task wherever technically feasible." },
  { id: 30, group: "Flour", cat: "Task",   sec: "Task-specific - Bulk Improver Addition in Flour Milling (FL6)",
    text: "Apply LEV enclosing the hopper feed tray." },
  { id: 31, group: "Flour", cat: "Task",   sec: "Task-specific - Bulk Improver Addition in Flour Milling (FL6)",
    text: "Use low-dust improver formulations (dust-suppressed products or low-dust granules); avoid weighing by using single-dose packets or whole bags wherever possible." },
  { id: 32, group: "Flour", cat: "Task",   sec: "Task-specific - Bulk Improver Addition in Flour Milling (FL6)",
    text: "Train workers to tip additives gently into the hopper - never dump. Ensure empty bags are rolled up with the open end within the extraction zone." },

  { id: 33, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "RPE with a UK Standard Assigned Protection Factor (APF) of at least 20 is required for the manual addition of bulk improvers to flour in milling operations (FL6) - this is in addition to engineering controls, not instead of them." },
  { id: 34, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Provide RPE for all maintenance and cleaning activities associated with flour handling equipment and LEV systems." },
  { id: 35, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Where tight-fitting RPE is used: fit testing is mandatory; workers must be clean-shaven; train workers in correct donning, doffing, and pre-use checks." },
  { id: 36, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Disposable RPE must be discarded at the end of each shift, or sooner if it becomes blocked." },
  { id: 37, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Replace reusable respirator filters in accordance with manufacturer guidance and whenever filters are past shelf-life, visibly damaged or contaminated, or breathing resistance increases." },
  { id: 38, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Carry out RPE examination and testing at least monthly (or before each use if infrequent - intervals must not exceed three months)." },
  { id: 39, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Where RPE is required for periods exceeding one hour, provide powered air-purifying respirators (PAPR) or constant-flow airline breathing apparatus." },
  { id: 40, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Keep all RPE clean and store in a clean, designated location when not in use." },

  { id: 41, group: "Flour", cat: "PPE",    sec: "PPE & Skin Protection",
    text: "Provide coveralls that do not retain dust; arrange laundering through a contract laundry service - workers must not launder work clothing at home." },
  { id: 42, group: "Flour", cat: "PPE",    sec: "PPE & Skin Protection",
    text: "Provide warm water, mild skin cleansers, and soft paper or fabric towels at all wash stations - avoid abrasive cleansers." },
  { id: 43, group: "Flour", cat: "PPE",    sec: "PPE & Skin Protection",
    text: "Provide pre-work emollient skin creams to facilitate post-work skin cleansing." },
  { id: 44, group: "Flour", cat: "PPE",    sec: "PPE & Skin Protection",
    text: "Provide after-work emollient creams to replenish skin lipids following handwashing." },
  { id: 45, group: "Flour", cat: "PPE",    sec: "PPE & Skin Protection",
    text: "Note: barrier creams do not constitute a complete physical barrier and must not be used as a substitute for other protective measures." },

  { id: 46, group: "Flour", cat: "Maint",  sec: "Maintenance, Examination & Testing",
    text: "LEV systems are subject to a statutory Thorough Examination and Test (TExT) under COSHH Regulation 9; this must be carried out by a competent person at intervals not exceeding 14 months." },
  { id: 47, group: "Flour", cat: "Maint",  sec: "Maintenance, Examination & Testing",
    text: "Carry out a visual check of all control equipment for signs of damage or deterioration before commencing work each day." },
  { id: 48, group: "Flour", cat: "Maint",  sec: "Maintenance, Examination & Testing",
    text: "Maintain a LEV user manual or log book recording performance specifications, inspection frequency, maintenance schedules, and parts replacement history." },
  { id: 49, group: "Flour", cat: "Maint",  sec: "Maintenance, Examination & Testing",
    text: "Retain records of all LEV examinations and tests for a minimum of 5 years." },
  { id: 50, group: "Flour", cat: "Maint",  sec: "Maintenance, Examination & Testing",
    text: "Act on all remedial actions identified by TExT reports without undue delay." },
  { id: 51, group: "Flour", cat: "Maint",  sec: "Maintenance, Examination & Testing",
    text: "Effectiveness of controls should be verified using qualitative dust lamp (Tyndall beam) checks or quantitative air sampling for higher-risk scenarios - refer to HSG258." },

  { id: 52, group: "Flour", cat: "Clean",  sec: "Cleaning & Housekeeping",
    text: "Clean work equipment and the immediate work area at the end of each shift (daily minimum)." },
  { id: 53, group: "Flour", cat: "Clean",  sec: "Cleaning & Housekeeping",
    text: "Clean the wider workroom, including overhead beams, heating pipework, and light fittings, at least once per week." },
  { id: 54, group: "Flour", cat: "Clean",  sec: "Cleaning & Housekeeping",
    text: "Remove dry flour dust by vacuum cleaning or wet methods only - vacuum equipment must meet at least dust Class M (medium hazard) classification." },
  { id: 55, group: "Flour", cat: "Clean",  sec: "Cleaning & Housekeeping",
    text: "Deal with flour spills immediately; shovel large spills carefully into a waste bag or spill hopper." },
  { id: 56, group: "Flour", cat: "Clean",  sec: "Cleaning & Housekeeping",
    text: "Never use brushes or compressed air to remove dust from clothing, skin, or equipment surfaces - these methods disperse dust into the breathing zone." },

  { id: 57, group: "Flour", cat: "Health", sec: "Health Surveillance",
    text: "Implement a health surveillance programme for occupational asthma where there is a reasonable likelihood of asthma developing (refer to HSE G402)." },
  { id: 58, group: "Flour", cat: "Health", sec: "Health Surveillance",
    text: "Implement a health surveillance programme for occupational dermatitis where there is a reasonable likelihood of dermatitis developing (refer to HSE G403)." },
  { id: 59, group: "Flour", cat: "Health", sec: "Health Surveillance",
    text: "Inform workers of the early signs and symptoms of occupational asthma and contact dermatitis and advise them to report any symptoms to their line manager promptly." },

  { id: 60, group: "Flour", cat: "Train",  sec: "Training & Supervision",
    text: "Permit access to flour handling areas to authorised and appropriately trained personnel only." },
  { id: 61, group: "Flour", cat: "Train",  sec: "Training & Supervision",
    text: "Provide documented training covering: health hazards of flour dust and enzyme improvers; correct use and checking of LEV; correct use, maintenance, and storage of RPE and PPE; and actions in the event of control failure." },
  { id: 62, group: "Flour", cat: "Train",  sec: "Training & Supervision",
    text: "Maintain training records as evidence that training has been delivered and understood." },
  { id: 63, group: "Flour", cat: "Train",  sec: "Training & Supervision",
    text: "Review and update training whenever work processes, substances, or LEV systems change." },
  { id: 64, group: "Flour", cat: "Train",  sec: "Training & Supervision",
    text: "Include managers and supervisors in all relevant health and safety training." },
  { id: 65, group: "Flour", cat: "Train",  sec: "Training & Supervision",
    text: "Provide active supervision to ensure safe work procedures are consistently followed." },

  { id: 66, group: "Flour", cat: "Exp",    sec: "Occupational Exposure Benchmark",
    text: "When all COSHH controls are correctly implemented, flour dust concentrations of less than 2 mg/m\u00b3 (8-hour TWA) should be achievable at all assessed tasks." },
  { id: 67, group: "Flour", cat: "Exp",    sec: "Occupational Exposure Benchmark",
    text: "Where monitoring results exceed 2 mg/m\u00b3 TWA, controls should be reviewed and remedial actions implemented before re-sampling." },
  { id: 68, group: "Flour", cat: "Exp",    sec: "Occupational Exposure Benchmark",
    text: "The Workplace Exposure Limit (WEL) for flour dust is 10 mg/m\u00b3 (8-hr TWA); the HSE recommends exposure be reduced as far below the WEL as reasonably practicable - 2 mg/m\u00b3 represents good control practice performance." },

  // ═══════════════════════════════════════════════════
  // AGRICULTURE - HSE AG Series
  // ═══════════════════════════════════════════════════

  { id: 69,  group: "Agriculture", cat: "Cab",    sec: "Harvesting Grain & Seed Crops (AG1)",
    text: "Use a combine harvester with an enclosed, ventilated cab fitted with filtered air intakes; confirm clean air is turned on and self-test every time the harvester is started." },
  { id: 70,  group: "Agriculture", cat: "Cab",    sec: "Harvesting Grain & Seed Crops (AG1)",
    text: "Close cab doors and windows at all times during harvesting to keep dust out." },
  { id: 71,  group: "Agriculture", cat: "Cab",    sec: "Harvesting Grain & Seed Crops (AG1)",
    text: "Where reasonably practicable, use a tractor with an enclosed, ventilated cab fitted with filtered air intakes for trailers collecting grain; try to stay upwind of dust clouds." },
  { id: 72,  group: "Agriculture", cat: "RPE",    sec: "Harvesting Grain & Seed Crops (AG1)",
    text: "Provide RPE with a UK Standard APF of at least 10 for maintenance, cleaning inside machinery, or where dust clouds are unavoidable." },
  { id: 73,  group: "Agriculture", cat: "Maint",  sec: "Harvesting Grain & Seed Crops (AG1)",
    text: "Carry out daily checks of vehicle cab filtration: inspect door and window seals, check pre-filters, verify filter seating condition, and change HEPA inlet air filters as advised by the manufacturer." },
  { id: 74,  group: "Agriculture", cat: "Clean",  sec: "Harvesting Grain & Seed Crops (AG1)",
    text: "Clean the cab at least once a week during harvest using vacuum equipment meeting at least dust Class M classification or wet cleaning methods - never use brushes or compressed air." },
  { id: 75,  group: "Agriculture", cat: "Maint",  sec: "Harvesting Grain & Seed Crops (AG1)",
    text: "Keep records of all equipment examinations for at least 5 years; get a competent engineer to examine vehicle air filtration at suitable intervals." },

  { id: 76,  group: "Agriculture", cat: "Task",   sec: "Grain & Seed Transfer, Small Scale (AG2)",
    text: "Segregate the tipping point from the grain store; where possible turn on the equipment and leave the area before dust is generated." },
  { id: 77,  group: "Agriculture", cat: "Task",   sec: "Grain & Seed Transfer, Small Scale (AG2)",
    text: "Minimise dust escapes by enclosing the tipping point with plastic strip curtains and discharging into covered storage bins through a sock." },
  { id: 78,  group: "Agriculture", cat: "LEV",    sec: "Grain & Seed Transfer, Small Scale (AG2)",
    text: "Apply LEV at the source of exposure; use enclosed or extracted elevators and conveyors; airflow must be sufficient to control airborne contaminants effectively." },
  { id: 79,  group: "Agriculture", cat: "LEV",    sec: "Grain & Seed Transfer, Small Scale (AG2)",
    text: "Provide an airflow indicator on LEV systems and mark the acceptable range of readings on the gauge; keep extraction ducts short and simple." },
  { id: 80,  group: "Agriculture", cat: "Maint",  sec: "Grain & Seed Transfer, Small Scale (AG2)",
    text: "LEV systems require a statutory TExT by a competent person at intervals not exceeding 14 months; retain records of all examinations for at least 5 years." },
  { id: 81,  group: "Agriculture", cat: "RPE",    sec: "Grain & Seed Transfer, Small Scale (AG2)",
    text: "Provide RPE with a UK Standard APF of at least 10 for maintenance, cleaning, or where dust clouds cannot be avoided; examine and test non-disposable RPE at least monthly." },
  { id: 82,  group: "Agriculture", cat: "Clean",  sec: "Grain & Seed Transfer, Small Scale (AG2)",
    text: "Clean work equipment and the work area daily; clean other equipment at least once a week; use vacuum equipment meeting at least dust Class M classification." },

  { id: 83,  group: "Agriculture", cat: "Task",   sec: "Weighing, Milling & Mixing Animal Feeds (AG3)",
    text: "Avoid weighing out additives where possible - buy in one-shot packages; consider suppressing dust by using molasses or oil in the feed formula." },
  { id: 84,  group: "Agriculture", cat: "LEV",    sec: "Weighing, Milling & Mixing Animal Feeds (AG3)",
    text: "Fit the hopper, mixer and bagging-off point with LEV; fit lids where dust can escape and enclose chutes; auger mixed feed to storage bins." },
  { id: 85,  group: "Agriculture", cat: "LEV",    sec: "Weighing, Milling & Mixing Animal Feeds (AG3)",
    text: "When operating inside a shed provide general ventilation with greater than five air changes per hour with a through draught; discharge extracted air away from doors, windows and air inlets." },
  { id: 86,  group: "Agriculture", cat: "Task",   sec: "Weighing, Milling & Mixing Animal Feeds (AG3)",
    text: "Place machinery controls outside the working area and provide an emergency stop near the machine; in larger plants, provide a separate control room." },
  { id: 87,  group: "Agriculture", cat: "Cab",    sec: "Weighing, Milling & Mixing Animal Feeds (AG3)",
    text: "Where a vehicle is used, use one with an enclosed, ventilated cab fitted with filtered air intakes; check clean air is working and self-test every time the vehicle is started; keep doors and windows closed." },
  { id: 88,  group: "Agriculture", cat: "RPE",    sec: "Weighing, Milling & Mixing Animal Feeds (AG3)",
    text: "Provide RPE with a UK Standard APF of at least 10 for maintenance, cleaning, or unavoidable dust exposure; if RPE is required for more than 1 hour, use powered respirators." },

  { id: 89,  group: "Agriculture", cat: "Task",   sec: "Feeding Livestock Housed Indoors (AG4)",
    text: "Automate feeding where possible using enclosed elevators, conveyors or an auger; use pelletised or slurry feeds which produce less dust." },
  { id: 90,  group: "Agriculture", cat: "Task",   sec: "Feeding Livestock Housed Indoors (AG4)",
    text: "Where manual feeding cannot be avoided, pour feed gently - never throw or dump it." },
  { id: 91,  group: "Agriculture", cat: "RPE",    sec: "Feeding Livestock Housed Indoors (AG4)",
    text: "Provide RPE with a UK Standard APF of at least 10 for all dusty operations; workers wearing tight-fitting RPE must be clean-shaven and trained in correct fit, use and maintenance." },
  { id: 92,  group: "Agriculture", cat: "RPE",    sec: "Feeding Livestock Housed Indoors (AG4)",
    text: "Examine and test non-disposable RPE at least once per month; keep RPE clean and store in a clean place; discard disposable RPE at the end of each shift or sooner if blocked." },
  { id: 93,  group: "Agriculture", cat: "Health", sec: "Feeding Livestock Housed Indoors (AG4)",
    text: "Provide health surveillance for occupational asthma and dermatitis where there is a reasonable likelihood these may occur (refer to HSE G402 and G403)." },

  { id: 94,  group: "Agriculture", cat: "Task",   sec: "Grain & Seed Cleaning, Fixed & Mobile (AG5)",
    text: "If possible, locate mobile plant outside; indoors, provide general ventilation with greater than five clean air changes per hour and a through draught." },
  { id: 95,  group: "Agriculture", cat: "LEV",    sec: "Grain & Seed Cleaning, Fixed & Mobile (AG5)",
    text: "Fit the machine hopper, cleaning head and bagging-off point with LEV; roll up empty bags with the open end in a dust extraction zone or do this outside." },
  { id: 96,  group: "Agriculture", cat: "Task",   sec: "Grain & Seed Cleaning, Fixed & Mobile (AG5)",
    text: "If not bagging, discharge cleaned seed into a covered storage container through a sock; discharge extracted air to a safe place away from doors, windows and air inlets." },
  { id: 97,  group: "Agriculture", cat: "Task",   sec: "Grain & Seed Cleaning, Fixed & Mobile (AG5)",
    text: "Move seed gently - never throw or dump it; for seed dressing products, follow all handling instructions on the product label." },
  { id: 98,  group: "Agriculture", cat: "Maint",  sec: "Grain & Seed Cleaning, Fixed & Mobile (AG5)",
    text: "LEV systems require a statutory TExT at intervals not exceeding 14 months; permit-to-work procedures may be required for maintenance activities." },

  { id: 99,  group: "Agriculture", cat: "Task",   sec: "Opening Hay, Haylage & Silage Bales (AG6)",
    text: "Handle hay, haylage and silage gently at all times to avoid stirring up dust and spores." },
  { id: 100, group: "Agriculture", cat: "RPE",    sec: "Opening Hay, Haylage & Silage Bales (AG6)",
    text: "Provide RPE with a UK Standard APF of at least 10 for all dusty bale-opening operations; examine and test non-disposable RPE at least monthly." },
  { id: 101, group: "Agriculture", cat: "PPE",    sec: "Opening Hay, Haylage & Silage Bales (AG6)",
    text: "Provide protective coveralls; ask your supplier to advise on suitable PPE for bale handling." },
  { id: 102, group: "Agriculture", cat: "Health", sec: "Opening Hay, Haylage & Silage Bales (AG6)",
    text: "Provide health surveillance for occupational asthma where there is a reasonable likelihood it may occur (refer to HSE G402)." },

  { id: 103, group: "Agriculture", cat: "Cab",    sec: "Composting (AG7)",
    text: "Where reasonably practicable use a vehicle with an enclosed, ventilated cab fitted with filtered air intakes for moving compost; keep doors and windows closed; if not possible, wear RPE." },
  { id: 104, group: "Agriculture", cat: "LEV",    sec: "Composting (AG7)",
    text: "Apply LEV at the source of exposure for conveyors, screens and transfer points; use enclosed or extracted elevators, conveyors and screens; discharge extracted air away from doors, windows and air inlets." },
  { id: 105, group: "Agriculture", cat: "LEV",    sec: "Composting (AG7)",
    text: "Provide an airflow indicator on all LEV and mark the acceptable operating range on the gauge; keep ducts short and simple." },
  { id: 106, group: "Agriculture", cat: "Maint",  sec: "Composting (AG7)",
    text: "Carry out daily checks of vehicle cab filtration including door and window seals, pre-filters, filter seating and HEPA filters; get a competent engineer to examine air filtration at suitable intervals." },
  { id: 107, group: "Agriculture", cat: "RPE",    sec: "Composting (AG7)",
    text: "Provide RPE with a UK Standard APF of at least 10 for maintenance, cleaning, or where dust/bioaerosol clouds are unavoidable; use powered respirators if RPE is required for more than 1 hour." },
  { id: 108, group: "Agriculture", cat: "Maint",  sec: "Composting (AG7)",
    text: "LEV systems require a statutory TExT at intervals not exceeding 14 months; retain all examination records for at least 5 years." },

  { id: 109, group: "Agriculture", cat: "Cab",    sec: "Straw Chopping & Blowing (AG8)",
    text: "Use a vehicle with an enclosed, ventilated cab fitted with filtered air intakes; try to keep upwind of dust clouds; keep doors and windows closed throughout the operation." },
  { id: 110, group: "Agriculture", cat: "Task",   sec: "Straw Chopping & Blowing (AG8)",
    text: "Provide general ventilation with greater than five air changes per hour using powered wall- or window-mounted fans with a through draught." },
  { id: 111, group: "Agriculture", cat: "Task",   sec: "Straw Chopping & Blowing (AG8)",
    text: "Allow a minimum of 10 minutes for dust to settle before entering the building after straw chopping or blowing - or wear RPE on entry." },
  { id: 112, group: "Agriculture", cat: "RPE",    sec: "Straw Chopping & Blowing (AG8)",
    text: "Wear RPE when using hand-push straw choppers; provide RPE with a UK Standard APF of at least 10 for maintenance, cleaning, or unavoidable dust exposure." },
  { id: 113, group: "Agriculture", cat: "Maint",  sec: "Straw Chopping & Blowing (AG8)",
    text: "Carry out daily checks of vehicle cab filtration: door and window seals, pre-filters, filter seating and HEPA inlet air filters; clean the cab at least once a week using Class M vacuum equipment or wet methods." },

  { id: 114, group: "Agriculture", cat: "Clean",  sec: "Cleaning Grain & Feed Stores, Sheds & Silos (AG9)",
    text: "Remove as much dust as possible by mechanical means and vacuum cleaning before applying any chemical cleaning products; avoid dry brushing and compressed air wherever possible." },
  { id: 115, group: "Agriculture", cat: "Task",   sec: "Cleaning Grain & Feed Stores, Sheds & Silos (AG9)",
    text: "Check safety data sheets for all cleaning chemicals; substitute with safer products where possible; avoid products labelled 'may cause sensitisation by inhalation or skin contact'." },
  { id: 116, group: "Agriculture", cat: "RPE",    sec: "Cleaning Grain & Feed Stores, Sheds & Silos (AG9)",
    text: "Provide RPE with a UK Standard APF of at least 20; depending on products used, a combination filter for dust and vapour may be required; workers must put on RPE before entering the area." },
  { id: 117, group: "Agriculture", cat: "RPE",    sec: "Cleaning Grain & Feed Stores, Sheds & Silos (AG9)",
    text: "Provide air-fed breathing apparatus for work in confined spaces such as closed silos or conveyor boots, or where compressed air is used for cleaning." },
  { id: 118, group: "Agriculture", cat: "PPE",    sec: "Cleaning Grain & Feed Stores, Sheds & Silos (AG9)",
    text: "Provide PPE to minimise skin contact with chemicals; nitrile gloves are typically acceptable - check product labels; consider safe access arrangements for working at height." },
  { id: 119, group: "Agriculture", cat: "Clean",  sec: "Cleaning Grain & Feed Stores, Sheds & Silos (AG9)",
    text: "Deal with chemical spills immediately using suitable protective gloves; clean work equipment at least once a week." },

  { id: 120, group: "Agriculture", cat: "Task",   sec: "On-Farm Cleaning & Grading of Bulbs, Roots & Tubers (AG10)",
    text: "Segregate the tipping point and cleaning machine from power controls and other work areas; minimise time workers spend next to running machines." },
  { id: 121, group: "Agriculture", cat: "LEV",    sec: "On-Farm Cleaning & Grading of Bulbs, Roots & Tubers (AG10)",
    text: "Apply LEV at the source of exposure for cleaning machines, elevators, conveyors, grading machines and bagging-off points; airflow must be sufficient to effectively capture airborne contaminants." },
  { id: 122, group: "Agriculture", cat: "LEV",    sec: "On-Farm Cleaning & Grading of Bulbs, Roots & Tubers (AG10)",
    text: "Provide general ventilation with greater than five air changes per hour using powered wall- or window-mounted fans with a through draught; mark the acceptable range of readings on LEV gauges." },
  { id: 123, group: "Agriculture", cat: "Exp",    sec: "On-Farm Cleaning & Grading of Bulbs, Roots & Tubers (AG10)",
    text: "Keep exposures to respirable crystalline silica (RCS) below 0.1 mg/m\u00b3 (8-hour TWA) - dry soil associated with bulbs, roots and tubers may contain silica." },
  { id: 124, group: "Agriculture", cat: "PPE",    sec: "On-Farm Cleaning & Grading of Bulbs, Roots & Tubers (AG10)",
    text: "Provide overalls that do not retain dust (smooth synthetic fabrics, not cotton or knitted); provide single-use nitrile gloves - handling bulbs, roots and tubers without gloves can cause dermatitis." },
  { id: 125, group: "Agriculture", cat: "RPE",    sec: "On-Farm Cleaning & Grading of Bulbs, Roots & Tubers (AG10)",
    text: "Provide RPE with a UK Standard APF of at least 10 for maintenance, cleaning, or unavoidable dust exposure; LEV systems require a statutory TExT at intervals not exceeding 14 months." },
  { id: 126, group: "Agriculture", cat: "Health", sec: "On-Farm Cleaning & Grading of Bulbs, Roots & Tubers (AG10)",
    text: "Provide health surveillance for occupational asthma and dermatitis where there is a reasonable likelihood these may occur (refer to HSE G402 and G403)." },
];
