const RECOMMENDATIONS = [

  // ═══════════════════════════════════════════════════
  // FLOUR DUST - HSE FL Series
  // ═══════════════════════════════════════════════════

  { id: 1,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Install LEV at the source of dust generation for all flour handling tasks, including bag opening, tipping, dough mixing, moulding, dividing, bagging, and improver handling." },
  { id: 2,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "A permanent, fixed dust extraction system is the preferred option; a stand-alone mobile dust collector is acceptable only where fixed installation is not reasonably practicable." },
  { id: 3,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Enclose the process as much as possible - use see-through panels and plastic strip curtains to reduce open areas while maintaining safe access." },
  { id: 4,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Airflow velocity must be sufficient to effectively capture airborne contaminants. Adequacy will depend on hood/enclosure design, opening size, and the specific process and substance." },
  { id: 5,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Keep extraction ductwork as short and direct as possible; avoid long runs of flexible ducting." },
  { id: 6,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Position work areas away from doors, windows, and walkways to prevent draughts from disrupting LEV performance and dispersing airborne dust." },
  { id: 7,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Discharge extracted air to a safe external location, away from doors, windows, and fresh air inlets." },
  { id: 8,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Fit airflow indicators or equivalent devices on all LEV systems to allow workers to confirm the system is operating before commencing work." },
  { id: 9,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Fit filter blockage/failure indicator alarms to all LEV and stand-alone dust collector units." },
  { id: 10, group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Confirm LEV is switched on and functioning correctly at the start of each work period - check the gauge." },
  { id: 11, group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "For stand-alone dust collectors: the unit must not release dust on start-up and should recirculate clean air; a secondary filter meeting at least dust Type M (medium hazard) classification is required for workplace recirculation." },
  { id: 12, group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Do not allow the waste bag on stand-alone units to overfill - check gauges regularly and keep sufficient spare filters and bags on site." },
  { id: 13, group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Provide a good standard of general (dilution) ventilation throughout the work area to supplement LEV." },

  { id: 14, group: "Flour", cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
    text: "Apply LEV with rim extraction at the tipping/mixing point; put a solid lid on the mixer where practicable." },
  { id: 15, group: "Flour", cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
    text: "Tip flour gently - never dump. Add ingredients gently, trickle water down the inside of the bowl, and start the mixer on slow speed." },
  { id: 16, group: "Flour", cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
    text: "When crushing empty bags, roll them up with the open end positioned within the extraction zone to capture released dust." },
  { id: 17, group: "Flour", cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
    text: "Consider providing mechanical or pneumatic bag/sack handling assistance to reduce manual handling and dust generation." },

  { id: 18, group: "Flour", cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
    text: "Use LEV cabinet extraction when weighing flour improvers." },
  { id: 19, group: "Flour", cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
    text: "Substitute high-dust improvers with low-dust alternatives wherever possible, e.g. dust-suppressed products, low-dust granules, or paste formulations." },
  { id: 20, group: "Flour", cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
    text: "Eliminate weighing entirely where practicable by using single-dose packets." },
  { id: 21, group: "Flour", cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
    text: "Open improver containers with care to minimise dust release; keep used scoops and utensils inside the extraction cabinet until cleaned." },

  { id: 22, group: "Flour", cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
    text: "Apply LEV with extraction slots at the rear of the work table; keep extraction slots free from obstructions at all times." },
  { id: 23, group: "Flour", cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
    text: "Eliminate dusting with flour wherever possible - use non-stick table surfaces or food-grade oil as a lubricant." },
  { id: 24, group: "Flour", cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
    text: "Where dusting cannot be avoided, workers should cast flour gently towards the extraction slots rather than across the open workspace." },
  { id: 25, group: "Flour", cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
    text: "Provide easy access to remove dust build-up behind extraction slots." },

  { id: 26, group: "Flour", cat: "Task",   sec: "Task-specific - Flour Bagging (FL5)",
    text: "Apply LEV enclosing the bagging point; use a filling nozzle that directs displaced air directly into the extraction system." },
  { id: 27, group: "Flour", cat: "Task",   sec: "Task-specific - Flour Bagging (FL5)",
    text: "Ensure the filling nozzle design does not spill flour when a bag is removed." },
  { id: 28, group: "Flour", cat: "Task",   sec: "Task-specific - Flour Bagging (FL5)",
    text: "Provide an extracted hopper at floor level to capture flour spills." },

  { id: 29, group: "Flour", cat: "Task",   sec: "Task-specific - Bulk Improver Addition in Flour Milling (FL6)",
    text: "Automate this task wherever technically feasible." },
  { id: 30, group: "Flour", cat: "Task",   sec: "Task-specific - Bulk Improver Addition in Flour Milling (FL6)",
    text: "Apply LEV enclosing the hopper feed tray." },
  { id: 31, group: "Flour", cat: "Task",   sec: "Task-specific - Bulk Improver Addition in Flour Milling (FL6)",
    text: "Use low-dust improver formulations (dust-suppressed products or low-dust granules); avoid weighing by using single-dose packets or whole bags wherever possible." },
  { id: 32, group: "Flour", cat: "Task",   sec: "Task-specific - Bulk Improver Addition in Flour Milling (FL6)",
    text: "Train workers to tip additives gently into the hopper - never dump. Ensure empty bags are rolled up with the open end within the extraction zone." },

  { id: 33, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "RPE with a UK Standard Assigned Protection Factor (APF) of at least 20 is required for the manual addition of bulk improvers to flour in milling operations (FL6) - this is in addition to engineering controls, not instead of them." },
  { id: 34, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Provide RPE for all maintenance and cleaning activities associated with flour handling equipment and LEV systems." },
  { id: 35, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Where tight-fitting RPE is used: fit testing is mandatory; workers must be clean-shaven; train workers in correct donning, doffing, and pre-use checks." },
  { id: 36, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Disposable RPE must be discarded at the end of each shift, or sooner if it becomes blocked." },
  { id: 37, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Replace reusable respirator filters in accordance with manufacturer guidance and whenever filters are past shelf-life, visibly damaged or contaminated, or breathing resistance increases." },
  { id: 38, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Carry out RPE examination and testing at least monthly (or before each use if infrequent - intervals must not exceed three months)." },
  { id: 39, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Where RPE is required for periods exceeding one hour, provide powered air-purifying respirators (PAPR) or constant-flow airline breathing apparatus." },
  { id: 40, group: "Flour", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Keep all RPE clean and store in a clean, designated location when not in use." },

  { id: 41, group: "Flour", cat: "PPE",    sec: "PPE & Skin Protection",
    text: "Provide coveralls that do not retain dust; arrange laundering through a contract laundry service - workers must not launder work clothing at home." },
  { id: 42, group: "Flour", cat: "PPE",    sec: "PPE & Skin Protection",
    text: "Provide warm water, mild skin cleansers, and soft paper or fabric towels at all wash stations - avoid abrasive cleansers." },
  { id: 43, group: "Flour", cat: "PPE",    sec: "PPE & Skin Protection",
    text: "Provide pre-work emollient skin creams to facilitate post-work skin cleansing." },
  { id: 44, group: "Flour", cat: "PPE",    sec: "PPE & Skin Protection",
    text: "Provide after-work emollient creams to replenish skin lipids following handwashing." },
  { id: 45, group: "Flour", cat: "PPE",    sec: "PPE & Skin Protection",
    text: "Note: barrier creams do not constitute a complete physical barrier and must not be used as a substitute for other protective measures." },

  { id: 46, group: "Flour", cat: "Maint",  sec: "Maintenance, Examination & Testing",
    text: "LEV systems are subject to a statutory Thorough Examination and Test (TExT) under COSHH Regulation 9; this must be carried out by a competent person at intervals not exceeding 14 months." },
  { id: 47, group: "Flour", cat: "Maint",  sec: "Maintenance, Examination & Testing",
    text: "Carry out a visual check of all control equipment for signs of damage or deterioration before commencing work each day." },
  { id: 48, group: "Flour", cat: "Maint",  sec: "Maintenance, Examination & Testing",
    text: "Maintain a LEV user manual or log book recording performance specifications, inspection frequency, maintenance schedules, and parts replacement history." },
  { id: 49, group: "Flour", cat: "Maint",  sec: "Maintenance, Examination & Testing",
    text: "Retain records of all LEV examinations and tests for a minimum of 5 years." },
  { id: 50, group: "Flour", cat: "Maint",  sec: "Maintenance, Examination & Testing",
    text: "Act on all remedial actions identified by TExT reports without undue delay." },
  { id: 51, group: "Flour", cat: "Maint",  sec: "Maintenance, Examination & Testing",
    text: "Effectiveness of controls should be verified using qualitative dust lamp (Tyndall beam) checks or quantitative air sampling for higher-risk scenarios - refer to HSG258." },

  { id: 52, group: "Flour", cat: "Clean",  sec: "Cleaning & Housekeeping",
    text: "Clean work equipment and the immediate work area at the end of each shift (daily minimum)." },
  { id: 53, group: "Flour", cat: "Clean",  sec: "Cleaning & Housekeeping",
    text: "Clean the wider workroom, including overhead beams, heating pipework, and light fittings, at least once per week." },
  { id: 54, group: "Flour", cat: "Clean",  sec: "Cleaning & Housekeeping",
    text: "Remove dry flour dust by vacuum cleaning or wet methods only - vacuum equipment must meet at least dust Class M (medium hazard) classification." },
  { id: 55, group: "Flour", cat: "Clean",  sec: "Cleaning & Housekeeping",
    text: "Deal with flour spills immediately; shovel large spills carefully into a waste bag or spill hopper." },
  { id: 56, group: "Flour", cat: "Clean",  sec: "Cleaning & Housekeeping",
    text: "Never use brushes or compressed air to remove dust from clothing, skin, or equipment surfaces - these methods disperse dust into the breathing zone." },

  { id: 57, group: "Flour", cat: "Health", sec: "Health Surveillance",
    text: "Implement a health surveillance programme for occupational asthma where there is a reasonable likelihood of asthma developing (refer to HSE G402)." },
  { id: 58, group: "Flour", cat: "Health", sec: "Health Surveillance",
    text: "Implement a health surveillance programme for occupational dermatitis where there is a reasonable likelihood of dermatitis developing (refer to HSE G403)." },
  { id: 59, group: "Flour", cat: "Health", sec: "Health Surveillance",
    text: "Tell workers to check their skin regularly for signs of dryness, cracking, redness, or soreness and to report any symptoms to their supervisor or occupational health provider." },

  { id: 60, group: "Flour", cat: "Train",  sec: "Training & Supervision",
    text: "Tell workers about the harmful nature of flour dust, including its potential to cause occupational asthma and dermatitis, and the importance of exposure controls." },
  { id: 61, group: "Flour", cat: "Train",  sec: "Training & Supervision",
    text: "Train workers on: when and how to use controls; how to check controls are working; correct use and maintenance of RPE; and what to do if something goes wrong." },
  { id: 62, group: "Flour", cat: "Train",  sec: "Training & Supervision",
    text: "Involve managers and supervisors in health and safety training and maintain training records." },

  // ═══════════════════════════════════════════════════
  // AGRICULTURE - HSE AG Series
  // ═══════════════════════════════════════════════════

  { id: 63, group: "Agriculture", cat: "Task",   sec: "Crop Spraying (AG1)",
    text: "Choose the least hazardous pesticide that is effective for the intended use; consult the safety data sheet and product label before use." },
  { id: 64, group: "Agriculture", cat: "Task",   sec: "Crop Spraying (AG1)",
    text: "Check weather conditions before spraying; do not spray in wind speeds above those specified on the product label; follow buffer zone requirements to protect water courses and non-target areas." },
  { id: 65, group: "Agriculture", cat: "PPE",    sec: "Crop Spraying (AG1)",
    text: "Wear the PPE specified on the product label during mixing, loading, and application; check the safety data sheet for any additional requirements beyond label PPE." },
  { id: 66, group: "Agriculture", cat: "PPE",    sec: "Crop Spraying (AG1)",
    text: "Provide overalls (ideally Tyvek or equivalent) that do not allow liquid penetration; provide chemical-resistant gloves, boots, and face protection as specified by the product label." },
  { id: 67, group: "Agriculture", cat: "Clean",  sec: "Crop Spraying (AG1)",
    text: "Decontaminate spray equipment thoroughly after use; rinse containers and dispose of washings as directed on the product label; store PPE separately from personal clothing." },

  { id: 68, group: "Agriculture", cat: "Task",   sec: "Sheep Dipping (AG2)",
    text: "Use a plunge dip or shower dip system; ensure the dip is maintained at the correct concentration using a refractometer or by following replenishment instructions." },
  { id: 69, group: "Agriculture", cat: "PPE",    sec: "Sheep Dipping (AG2)",
    text: "Wear impermeable gauntlet gloves, waterproof overalls or apron, waterproof boots, and a face shield during dipping; check gloves and overalls for damage before each use." },
  { id: 70, group: "Agriculture", cat: "Clean",  sec: "Sheep Dipping (AG2)",
    text: "Dispose of spent dip in accordance with product label instructions and relevant waste disposal regulations; never allow spent dip to enter watercourses." },

  { id: 71, group: "Agriculture", cat: "Task",   sec: "Grain Drying & Storage (AG3)",
    text: "Minimise handling of dried grain to reduce dust generation; use enclosed conveyors and augers where practicable." },
  { id: 72, group: "Agriculture", cat: "LEV",    sec: "Grain Drying & Storage (AG3)",
    text: "Apply LEV at transfer points, elevators, and filling points for grain stores; provide general ventilation with a through draught to dilute dust in grain store areas." },
  { id: 73, group: "Agriculture", cat: "RPE",    sec: "Grain Drying & Storage (AG3)",
    text: "Provide RPE with a UK Standard APF of at least 10 for work in grain stores, during grain tipping, or where dust exposure cannot otherwise be adequately controlled." },
  { id: 74, group: "Agriculture", cat: "Health", sec: "Grain Drying & Storage (AG3)",
    text: "Provide health surveillance for occupational asthma and farmer's lung (extrinsic allergic alveolitis) where there is a reasonable likelihood these may occur (refer to HSE G402)." },

  { id: 75, group: "Agriculture", cat: "Task",   sec: "Handling & Applying Fertilisers (AG4)",
    text: "Use enclosed cab tractors and application equipment wherever possible to reduce inhalation exposure to fertiliser dust." },
  { id: 76, group: "Agriculture", cat: "PPE",    sec: "Handling & Applying Fertilisers (AG4)",
    text: "Wear chemical-resistant gloves and overalls when handling concentrated fertilisers; follow safety data sheet guidance for PPE selection." },

  { id: 77, group: "Agriculture", cat: "Cab",    sec: "Enclosed Cab Controls (AG5)",
    text: "Use enclosed cab tractors and self-propelled machinery with a filtration system rated to BS EN 15695-1 Category 2 or higher for pesticide application; check that cab doors and windows close correctly before use." },
  { id: 78, group: "Agriculture", cat: "Cab",    sec: "Enclosed Cab Controls (AG5)",
    text: "Inspect and replace cab air filters at the frequency recommended by the manufacturer; keep a record of filter replacements." },
  { id: 79, group: "Agriculture", cat: "Cab",    sec: "Enclosed Cab Controls (AG5)",
    text: "Do not eat, drink, or smoke in the cab; decontaminate the cab interior at the end of each working day; arrange laundering of contaminated clothing through a contract laundry." },

  { id: 80, group: "Agriculture", cat: "Task",   sec: "Poultry Farming - Dust & Bioaerosols (AG6)",
    text: "Reduce litter disturbance during routine work; use water sprays to suppress dust during litter removal where practicable." },
  { id: 81, group: "Agriculture", cat: "RPE",    sec: "Poultry Farming - Dust & Bioaerosols (AG6)",
    text: "Provide RPE with a UK Standard APF of at least 20 (e.g. FFP3) for high-dust tasks such as litter removal, catching, and depopulation; provide powered air-purifying respirators for prolonged high-dust work." },
  { id: 82, group: "Agriculture", cat: "Health", sec: "Poultry Farming - Dust & Bioaerosols (AG6)",
    text: "Provide health surveillance for occupational asthma and extrinsic allergic alveolitis where there is a reasonable likelihood these may occur (refer to HSE G402)." },

  { id: 83, group: "Agriculture", cat: "Task",   sec: "Pig Farming - Dust & Bioaerosols (AG7)",
    text: "Use feed delivery systems that minimise the generation of feed dust; dampen feeds where practicable." },
  { id: 84, group: "Agriculture", cat: "RPE",    sec: "Pig Farming - Dust & Bioaerosols (AG7)",
    text: "Provide RPE with a UK Standard APF of at least 20 for high-dust tasks in pig buildings; provide powered air-purifying respirators for prolonged tasks." },

  { id: 85, group: "Agriculture", cat: "Task",   sec: "Mushroom Farming - Compost & Casing Handling (AG8)",
    text: "Enclose composting operations and transfer points wherever practicable; minimise manual disturbance of spawn-run and mature compost." },
  { id: 86, group: "Agriculture", cat: "RPE",    sec: "Mushroom Farming - Compost & Casing Handling (AG8)",
    text: "Provide RPE with a UK Standard APF of at least 20 for all work involving significant disturbance of compost or casing material, including filling, turning, and disposal." },
  { id: 87, group: "Agriculture", cat: "Health", sec: "Mushroom Farming - Compost & Casing Handling (AG8)",
    text: "Provide health surveillance for extrinsic allergic alveolitis (mushroom worker's lung) and occupational asthma where there is a reasonable likelihood these may occur (refer to HSE G402)." },

  { id: 88, group: "Agriculture", cat: "Task",   sec: "Bulb, Root & Tuber Cleaning - Silica Exposure (AG9)",
    text: "Keep exposures to respirable crystalline silica (RCS) below 0.1 mg/m3 (8-hour TWA); wet cleaning methods reduce the generation of silica-containing dust compared to dry processes." },
  { id: 89, group: "Agriculture", cat: "RPE",    sec: "Bulb, Root & Tuber Cleaning - Silica Exposure (AG9)",
    text: "Provide RPE with a UK Standard APF of at least 20 for tasks generating silica-containing dust that cannot be adequately controlled by LEV alone." },

  { id: 90, group: "Agriculture", cat: "Task",   sec: "Veterinary Medicines & Pesticides on Farm (AG11)",
    text: "Read and follow the product label and safety data sheet for all veterinary medicines and on-farm pesticides; use the least hazardous effective product available." },
  { id: 91, group: "Agriculture", cat: "PPE",    sec: "Veterinary Medicines & Pesticides on Farm (AG11)",
    text: "Wear the PPE specified on the product label; check PPE for damage before each use; store PPE separately from food and animal feed." },

  { id: 92, group: "Agriculture", cat: "Maint",  sec: "Maintenance, Examination & Testing",
    text: "LEV systems require a statutory TExT by a competent person at intervals not exceeding 14 months; retain records of all examinations and tests for at least 5 years." },
  { id: 93, group: "Agriculture", cat: "Maint",  sec: "Maintenance, Examination & Testing",
    text: "Carry out a visual check of all control equipment for signs of damage or deterioration before commencing work each day; check LEV airflow indicators are within the marked acceptable range." },

  { id: 94, group: "Agriculture", cat: "Clean",  sec: "Cleaning & Housekeeping",
    text: "Clean work equipment and work areas daily; clean the wider work environment at least weekly; remove organic debris that may support microbial growth." },
  { id: 95, group: "Agriculture", cat: "Clean",  sec: "Cleaning & Housekeeping",
    text: "Deal with spills immediately; use appropriate absorbent materials; dispose of contaminated materials as hazardous waste in accordance with applicable regulations." },

  { id: 96, group: "Agriculture", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Where tight-fitting RPE is used: fit testing is mandatory; workers must be clean-shaven; train workers in correct donning, doffing, and pre-use checks." },
  { id: 97, group: "Agriculture", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Where RPE is required for periods exceeding one hour, provide powered air-purifying respirators (PAPR) or constant-flow airline breathing apparatus." },
  { id: 98, group: "Agriculture", cat: "RPE",    sec: "Respiratory Protective Equipment",
    text: "Carry out RPE examination and testing at least monthly (or before each use if infrequent - intervals must not exceed three months); retain records." },

  { id: 99, group: "Agriculture", cat: "PPE",    sec: "PPE & Skin Protection",
    text: "Provide warm water, mild skin cleansers, and soft paper or fabric towels at all wash stations; provide pre-work and after-work emollient creams; note that barrier creams are not a substitute for other controls." },
  { id: 100, group: "Agriculture", cat: "PPE",   sec: "PPE & Skin Protection",
    text: "Arrange laundering of contaminated workwear through a contract laundry service - workers must not launder work clothing at home." },

  { id: 101, group: "Agriculture", cat: "Train", sec: "Training & Supervision",
    text: "Tell workers about the harmful nature of the substances and biological agents they handle, including the signs and symptoms of relevant occupational diseases." },
  { id: 102, group: "Agriculture", cat: "Train", sec: "Training & Supervision",
    text: "Train workers on: when and how to use controls; how to check controls are working; correct use and maintenance of RPE; and what to do if something goes wrong." },
  { id: 103, group: "Agriculture", cat: "Train", sec: "Training & Supervision",
    text: "Involve managers and supervisors in health and safety training and maintain training records." },

  { id: 104, group: "Agriculture", cat: "Health", sec: "Health Surveillance",
    text: "Provide health surveillance for occupational asthma where there is a reasonable likelihood it may develop (refer to HSE G402); maintain health surveillance records." },
  { id: 105, group: "Agriculture", cat: "Health", sec: "Health Surveillance",
    text: "Provide health surveillance for occupational dermatitis where there is a reasonable likelihood it may develop (refer to HSE G403); tell workers to check their skin regularly and report any symptoms." },

  { id: 106, group: "Agriculture", cat: "Task",   sec: "Horticulture - Pesticide Application in Glasshouses (AG12)",
    text: "Do not re-enter treated glasshouses until the re-entry interval stated on the product label has elapsed; post the re-entry time prominently at glasshouse entrances." },
  { id: 107, group: "Agriculture", cat: "PPE",    sec: "Horticulture - Pesticide Application in Glasshouses (AG12)",
    text: "Wear respiratory protection where required by the product label for glasshouse spraying; provide suitable RPE for re-entry where residual exposure risk remains." },

  { id: 108, group: "Agriculture", cat: "Task",   sec: "On-Farm Cleaning & Grading of Bulbs, Roots & Tubers (AG10)",
    text: "Segregate the tipping point and cleaning machine from power controls and other work areas; minimise time workers spend next to running machines." },
  { id: 109, group: "Agriculture", cat: "Task",   sec: "On-Farm Cleaning & Grading of Bulbs, Roots & Tubers (AG10)",
    text: "Enclose cleaning machines, elevators, conveyors, grading machines, and bagging-off points where practicable; use automated handling equipment to reduce manual product contact." },

  // ═══════════════════════════════════════════════════
  // Bulk sections referenced in the original file
  // ═══════════════════════════════════════════════════

  { id: 110, group: "Agriculture", cat: "LEV",    sec: "On-Farm Cleaning & Grading of Bulbs, Roots & Tubers (AG10)",
    text: "Apply LEV at the source of exposure for cleaning machines, elevators, conveyors, grading machines and bagging-off points; airflow must be sufficient to effectively capture airborne contaminants." },
  { id: 111, group: "Agriculture", cat: "LEV",    sec: "On-Farm Cleaning & Grading of Bulbs, Roots & Tubers (AG10)",
    text: "Provide general ventilation with greater than five air changes per hour using powered wall- or window-mounted fans with a through draught; mark the acceptable range of readings on LEV gauges." },
  { id: 112, group: "Agriculture", cat: "Exp",    sec: "On-Farm Cleaning & Grading of Bulbs, Roots & Tubers (AG10)",
    text: "Keep exposures to respirable crystalline silica (RCS) below 0.1 mg/m\u00b3 (8-hour TWA) - dry soil associated with bulbs, roots and tubers may contain silica." },
  { id: 113, group: "Agriculture", cat: "PPE",    sec: "On-Farm Cleaning & Grading of Bulbs, Roots & Tubers (AG10)",
    text: "Provide overalls that do not retain dust (smooth synthetic fabrics, not cotton or knitted); provide single-use nitrile gloves - handling bulbs, roots and tubers without gloves can cause dermatitis." },
  { id: 114, group: "Agriculture", cat: "RPE",    sec: "On-Farm Cleaning & Grading of Bulbs, Roots & Tubers (AG10)",
    text: "Provide RPE with a UK Standard APF of at least 10 for maintenance, cleaning, or unavoidable dust exposure; LEV systems require a statutory TExT at intervals not exceeding 14 months." },
  { id: 115, group: "Agriculture", cat: "Health", sec: "On-Farm Cleaning & Grading of Bulbs, Roots & Tubers (AG10)",
    text: "Provide health surveillance for occupational asthma and dermatitis where there is a reasonable likelihood these may occur (refer to HSE G402 and G403)." },

  // ═══════════════════════════════════════════════════
  // METALWORKING FLUIDS - HSE MW Series
  // ═══════════════════════════════════════════════════

  // MW1 - CNC Machining
  { id: 116, group: "Metalworking Fluids", cat: "LEV",   sec: "CNC Machining - LEV & Engineering Controls (MW1)",
    text: "Enclose CNC machines as much as possible, e.g. retrofitting roof panels, to minimise escape of MWF mist." },
  { id: 117, group: "Metalworking Fluids", cat: "LEV",   sec: "CNC Machining - LEV & Engineering Controls (MW1)",
    text: "Provide LEV to the CNC enclosure, either as a standalone unit or a centralised system. Design considerations must include volume flow rate, location of extraction points, enclosure dimensions and the level of mist generated." },
  { id: 118, group: "Metalworking Fluids", cat: "LEV",   sec: "CNC Machining - LEV & Engineering Controls (MW1)",
    text: "Discharge extracted air to a safe place outside the building, away from doors, windows and air inlets. If recirculated back into the workshop, ensure a suitable high efficiency air cleaning device is in place." },
  { id: 119, group: "Metalworking Fluids", cat: "LEV",   sec: "CNC Machining - LEV & Engineering Controls (MW1)",
    text: "Provide an easy way of checking the LEV is working, e.g. airflow indicator or equivalent; check for swarf accumulating around the extraction point before starting work." },
  { id: 120, group: "Metalworking Fluids", cat: "Task",  sec: "CNC Machining - LEV & Engineering Controls (MW1)",
    text: "Apply MWF at the lowest possible pressure and flow volume consistent with adequate lubrication, cooling and swarf removal; apply at the point of tool-workpiece contact to minimise mist generation from other rotating parts." },
  { id: 121, group: "Metalworking Fluids", cat: "Task",  sec: "CNC Machining - LEV & Engineering Controls (MW1)",
    text: "Stop MWF delivery when not machining, but maintain fluid circulation to prevent stagnation (see MW5 Managing fluid quality)." },
  { id: 122, group: "Metalworking Fluids", cat: "Task",  sec: "CNC Machining - LEV & Engineering Controls (MW1)",
    text: "Observe a time delay between the machine stopping and opening the enclosure doors to ensure no mist is present in the operator's breathing zone (within 20-30 cm of nose and mouth). Implement via machine programme or timer." },
  { id: 123, group: "Metalworking Fluids", cat: "Task",  sec: "CNC Machining - LEV & Engineering Controls (MW1)",
    text: "Avoid using compressed air guns to clean components - use alternatives such as vacuum guns, absorbent materials, low pressure coolant guns, spindle-mounted fans or automatic compressed air hoses operated with enclosure doors shut." },
  { id: 124, group: "Metalworking Fluids", cat: "Task",  sec: "CNC Machining - LEV & Engineering Controls (MW1)",
    text: "Where compressed air guns cannot be avoided: reduce exit pressure to as low as practicable (30 psi/2.1 bar is effective); use longer lances (e.g. 30 cm); blow down components inside the machine with LEV operating. Never use compressed air for cleaning skin or clothing." },
  { id: 125, group: "Metalworking Fluids", cat: "Task",  sec: "CNC Machining - LEV & Engineering Controls (MW1)",
    text: "Use suitable swarf vacuums to remove wet swarf/chips from machine surfaces. Finished components can be cleaned in industrial washing/degreasing machines." },
  { id: 126, group: "Metalworking Fluids", cat: "Maint", sec: "CNC Machining - LEV & Engineering Controls (MW1)",
    text: "Carry out weekly checks for signs of damage to flexible ducts and filter housings; repair faulty extraction systems promptly." },
  { id: 127, group: "Metalworking Fluids", cat: "Maint", sec: "CNC Machining - LEV & Engineering Controls (MW1)",
    text: "LEV systems require a statutory TExT by a competent person at intervals not exceeding 14 months; retain records of all examinations and tests for at least 5 years; carry out all remedial actions arising from the TExT." },
  { id: 128, group: "Metalworking Fluids", cat: "Maint", sec: "CNC Machining - LEV & Engineering Controls (MW1)",
    text: "Maintain an LEV system logbook containing schedules and records of regular checking, maintenance and repair. Where no logbook, user manual or commissioning report exists, seek help from a competent person such as an occupational hygienist specialising in LEV." },
  { id: 129, group: "Metalworking Fluids", cat: "Health", sec: "CNC Machining - LEV & Engineering Controls (MW1)",
    text: "Provide health surveillance where workers regularly inhale MWF mists and there is a reasonable likelihood that asthma may develop (refer to HSE G402); provide health surveillance for dermatitis where there is a reasonable likelihood it may occur (refer to HSE G403)." },
  { id: 130, group: "Metalworking Fluids", cat: "Train", sec: "CNC Machining - LEV & Engineering Controls (MW1)",
    text: "Train workers on: health hazards of MWF; how the LEV system works and how to check it; when and how to use alternatives to compressed air guns; how to use compressed air guns to minimise exposure; what to do if something goes wrong." },

  // MW2 - Control of skin risks during machining
  { id: 131, group: "Metalworking Fluids", cat: "Task",  sec: "Skin Risk Control During Machining (MW2)",
    text: "Select MWF carefully - consult your fluid supplier as there may be a fluid with less hazardous components; consider your selection as part of managing skin risks." },
  { id: 132, group: "Metalworking Fluids", cat: "Task",  sec: "Skin Risk Control During Machining (MW2)",
    text: "Minimise tramp oil leaks into the sump; remove tramp oil using mechanical skimmers, mobile oil coalescers or vacuum systems; remove fines using centrifuges, filtration systems or magnetic separators." },
  { id: 133, group: "Metalworking Fluids", cat: "Task",  sec: "Skin Risk Control During Machining (MW2)",
    text: "Mix fresh water-mix fluids to the supplier's recommended concentration. Top up only with fluid below recommended concentration as fluids evaporate and become more concentrated in use." },
  { id: 134, group: "Metalworking Fluids", cat: "Task",  sec: "Skin Risk Control During Machining (MW2)",
    text: "Do not add biocide until all good practice measures to maintain the fluid have been followed; add the right amount directly to the sump. Higher than recommended fluid or biocide concentration increases the risk of skin disease." },
  { id: 135, group: "Metalworking Fluids", cat: "Task",  sec: "Skin Risk Control During Machining (MW2)",
    text: "Prevent skin contact with MWF wherever possible; use automatic mixing devices instead of manual mixing; enclose machines as much as possible; reduce splash risks and provide properly designed splash-guards where not fully enclosed." },
  { id: 136, group: "Metalworking Fluids", cat: "Task",  sec: "Skin Risk Control During Machining (MW2)",
    text: "Use suitable tools (brushes, magnetic wands, swarf hooks) to remove swarf/chips from machine surfaces. Never remove swarf and fines from the sump by hand - use brushes, shovels and cut-resistant protective gloves." },
  { id: 137, group: "Metalworking Fluids", cat: "PPE",   sec: "Skin Risk Control During Machining (MW2)",
    text: "Provide single-use nitrile gloves suitable for controlling skin exposure to MWFs, but only where these do not add to other machinery risks such as entanglement; provide thicker gloves for cleaning and maintenance tasks (machinery switched off only)." },
  { id: 138, group: "Metalworking Fluids", cat: "PPE",   sec: "Skin Risk Control During Machining (MW2)",
    text: "Provide eye protection (goggles or safety glasses); provide overalls ensuring forearms are covered; ensure contaminated overalls are laundered before re-use using a contract laundry or suitable equivalent." },
  { id: 139, group: "Metalworking Fluids", cat: "PPE",   sec: "Skin Risk Control During Machining (MW2)",
    text: "Provide warm water, mild skin cleansers and soft paper or fabric towels at wash stations; provide pre-work creams and after-work creams to restore skin moisture. Note: barrier creams are not liquid gloves and do not provide a full barrier." },
  { id: 140, group: "Metalworking Fluids", cat: "Clean", sec: "Skin Risk Control During Machining (MW2)",
    text: "Keep surfaces clean to minimise MWF contact; deal with spills immediately using a vacuum system and absorbent materials; dispose of spilt MWF safely - do not return it to the machine as this contaminates the system." },
  { id: 141, group: "Metalworking Fluids", cat: "Health", sec: "Skin Risk Control During Machining (MW2)",
    text: "Provide health surveillance for dermatitis where there is a reasonable likelihood it may occur (refer to HSE G403); tell workers to check their skin regularly for dryness or soreness and report any symptoms." },

  // MW3 - Sump cleaning: water-mix fluids
  { id: 142, group: "Metalworking Fluids", cat: "Task",  sec: "Sump Cleaning - Water-mix Fluids (MW3)",
    text: "Decide on sump cleaning frequency based on visual inspection and monitoring results in consultation with the fluid supplier; provide equipment to remove and replace sump fluids with minimum spillage, e.g. wet vacuum." },
  { id: 143, group: "Metalworking Fluids", cat: "Task",  sec: "Sump Cleaning - Water-mix Fluids (MW3)",
    text: "Avoid the use of high pressure water hoses for sump cleaning where practicable; keep absorbent material to hand in case of spillages; follow the supplier's sump cleaning procedure including system cleaner type and circulation times." },
  { id: 144, group: "Metalworking Fluids", cat: "Task",  sec: "Sump Cleaning - Water-mix Fluids (MW3)",
    text: "Cleaning a large enclosed sump or underfloor tank may create a confined space risk - assess the risk and implement measures such as a permit-to-work system. Refer to Safe Work in Confined Spaces (L101) before undertaking any confined space work." },
  { id: 145, group: "Metalworking Fluids", cat: "Task",  sec: "Sump Cleaning - Water-mix Fluids (MW3)",
    text: "Follow the sump cleaning procedure: add system cleaner and circulate; empty and manually clean; clean hose connections, filters, splash screens and tramp oil separators; fill with fresh MWF at supplier's recommended concentration; test for bacteria after one week using dipslides." },
  { id: 146, group: "Metalworking Fluids", cat: "RPE",   sec: "Sump Cleaning - Water-mix Fluids (MW3)",
    text: "Provide RPE with a UK Standard APF of at least 20 (e.g. FFP3 or powered TH2) where mist is being generated, e.g. when using a high pressure water hose; use powered respirators or breathing apparatus if RPE is required for more than 1 hour continuously." },
  { id: 147, group: "Metalworking Fluids", cat: "RPE",   sec: "Sump Cleaning - Water-mix Fluids (MW3)",
    text: "If there is a risk of confined space working, select air-fed RPE; check the quality of the air supply to airline breathing apparatus at least every three months; visually check compressed airlines for signs of damage before each use." },
  { id: 148, group: "Metalworking Fluids", cat: "PPE",   sec: "Sump Cleaning - Water-mix Fluids (MW3)",
    text: "Provide thicker chemical and mechanical hazard-resistant gloves for sump cleaning (machinery switched off only); provide eye protection, overalls with forearms covered, and arrange contract laundering of contaminated workwear." },

  // MW4 - Sump cleaning: neat oils
  { id: 149, group: "Metalworking Fluids", cat: "Task",  sec: "Sump Cleaning - Neat Oils (MW4)",
    text: "Decide on sump cleaning frequency in consultation with the fluid supplier; provide equipment to remove and replace sump fluids with minimum spillage; keep absorbent material to hand in case of spillages." },
  { id: 150, group: "Metalworking Fluids", cat: "Task",  sec: "Sump Cleaning - Neat Oils (MW4)",
    text: "Follow the neat oil sump cleaning procedure: drain the oil; if contaminated, flush with compatible neat flushing oil and circulate; check flow rates and system integrity; drain and replace defective parts; refill with fresh neat oil." },
  { id: 151, group: "Metalworking Fluids", cat: "Task",  sec: "Sump Cleaning - Neat Oils (MW4)",
    text: "Assess confined space risk before cleaning large enclosed sumps or underfloor tanks; implement a permit-to-work system where required. Refer to Safe Work in Confined Spaces (L101)." },
  { id: 152, group: "Metalworking Fluids", cat: "PPE",   sec: "Sump Cleaning - Neat Oils (MW4)",
    text: "Provide thicker chemical and mechanical hazard-resistant gloves for neat oil sump cleaning (machinery switched off only); provide eye protection, overalls with forearms covered, and arrange contract laundering of contaminated workwear." },
  { id: 153, group: "Metalworking Fluids", cat: "PPE",   sec: "Sump Cleaning - Neat Oils (MW4)",
    text: "Remove clothing contaminated with neat oil immediately; provide warm water, mild skin cleansers and soft paper towels; provide pre-work and after-work emollient creams. Barrier creams are not a substitute for other controls." },
  { id: 154, group: "Metalworking Fluids", cat: "Clean", sec: "Sump Cleaning - Neat Oils (MW4)",
    text: "Deal with neat oil spills immediately using a vacuum system and absorbent materials; dispose of spilt neat oil safely - do not return it to the machine as this contaminates the system and reduces fluid life." },

  // MW5 - Managing fluid quality
  { id: 155, group: "Metalworking Fluids", cat: "Fluid", sec: "Managing Fluid Quality (MW5)",
    text: "Cover sumps to prevent contamination (e.g. from food, drinks, or other sources); minimise tramp oil leaks using mechanical skimmers, oil coalescers or vacuum systems; remove fines using centrifuges, filtration or magnetic separators." },
  { id: 156, group: "Metalworking Fluids", cat: "Fluid", sec: "Managing Fluid Quality (MW5)",
    text: "Prevent fluid stagnation in sumps and pipes by keeping fluid circulating with pumps; remove dead-ends and where practicable dead-legs; where dead-legs remain, flush at least weekly." },
  { id: 157, group: "Metalworking Fluids", cat: "Fluid", sec: "Managing Fluid Quality (MW5)",
    text: "When commissioning or modifying a MWF supply system, avoid points of low or no flow such as bottlenecks, dead-ends and dead-legs, which promote biofilm growth." },
  { id: 158, group: "Metalworking Fluids", cat: "Fluid", sec: "Managing Fluid Quality (MW5)",
    text: "Check input water quality for hardness, pH and bacteria; if using stored water, carry out weekly inspections of water storage tanks and filtration equipment." },
  { id: 159, group: "Metalworking Fluids", cat: "Fluid", sec: "Managing Fluid Quality (MW5)",
    text: "Check fluid appearance daily for unusual odour or biofilm deposits; measure fluid concentration (refractometer) and pH weekly; measure sump fluid temperature weekly; consider cooling the fluid if temperature rises significantly above workroom temperature." },
  { id: 160, group: "Metalworking Fluids", cat: "Fluid", sec: "Managing Fluid Quality (MW5)",
    text: "Check tramp oil content weekly - keep below 2%; check all strainers/filters regularly for blockages; check stored water tanks weekly for cleanliness." },
  { id: 161, group: "Metalworking Fluids", cat: "Fluid", sec: "Managing Fluid Quality (MW5)",
    text: "Take dipslides at least weekly; stir the sump before testing; use a dipslide incubator at consistent temperature; follow supplier's instructions for incubation time and temperature. Records of dipslide, concentration and pH tests can be used to justify reduced testing frequency." },
  { id: 162, group: "Metalworking Fluids", cat: "Fluid", sec: "Managing Fluid Quality (MW5)",
    text: "Dipslide results at or above 10^4 cfu/ml indicate microbial growth - first ensure all good practice fluid maintenance measures are in place before adding biocide. If bacterial growth continues, add biocide at supplier's recommended dose only, at a point of high turbulence." },
  { id: 163, group: "Metalworking Fluids", cat: "Fluid", sec: "Managing Fluid Quality (MW5)",
    text: "Dipslide results at or above 10^6 cfu/ml indicate poor control - act immediately by draining and cleaning the system. Do not add biocide as the sole response to high bacterial counts." },
  { id: 164, group: "Metalworking Fluids", cat: "Fluid", sec: "Managing Fluid Quality (MW5)",
    text: "Keep records of all fluid quality tests for at least five years; record results in a table or graph to identify trends; train personnel carrying out fluid quality checks on correct procedures, recording, result interpretation and remedial actions." },

  // ═══════════════════════════════════════════════════
  // LITHOGRAPHIC PRINTING - HSE P Series
  // ═══════════════════════════════════════════════════

  // P1 - Manual film and plate development
  { id: 176, group: "Lithographic Printing", cat: "Task",  sec: "Manual Film & Plate Development (P1)",
    text: "Consider whether it is reasonably practicable to use automated film and plate development (see P2) in preference to manual processes, to reduce the risk of skin contact with developers and fixers." },
  { id: 177, group: "Lithographic Printing", cat: "Task",  sec: "Manual Film & Plate Development (P1)",
    text: "Provide easy-to-clean work surfaces with lipped edges for liquid handling; keep developing solutions in shallow trays to contain spillage." },
  { id: 178, group: "Lithographic Printing", cat: "Task",  sec: "Manual Film & Plate Development (P1)",
    text: "Provide pumps or squeezable bottles for dispensing developing solutions in place of hand pouring." },
  { id: 179, group: "Lithographic Printing", cat: "Task",  sec: "Manual Film & Plate Development (P1)",
    text: "Screen UV exposure units with shutters, blinds or wraparound curtains to prevent UV light exposure to skin and eyes." },
  { id: 180, group: "Lithographic Printing", cat: "Task",  sec: "Manual Film & Plate Development (P1)",
    text: "Provide deletion pens in place of jars of hydrofluoric acid deletion fluid; stock calcium gluconate gel on site for first aid treatment of hydrofluoric acid burns and keep it readily accessible." },
  { id: 181, group: "Lithographic Printing", cat: "PPE",   sec: "Manual Film & Plate Development (P1)",
    text: "Provide splash-resistant single-use nitrile gloves (minimum 0.2 mm thick) for manual film and plate development; follow safety data sheet advice on glove selection for specific chemicals." },
  { id: 182, group: "Lithographic Printing", cat: "PPE",   sec: "Manual Film & Plate Development (P1)",
    text: "Provide eye protection and cotton overalls to minimise clothing contamination; tell workers to change immediately any heavily contaminated overalls and arrange laundering through a contract laundry - workers must not launder work clothing at home." },

  // P2 - Automated film and plate development
  { id: 183, group: "Lithographic Printing", cat: "Task",  sec: "Automated Film & Plate Development (P2)",
    text: "Use automatic processors with closed panels and closed liquid transfers, with solutions pumped from reservoirs to waste containers, to minimise skin contact with developers and fixers." },
  { id: 184, group: "Lithographic Printing", cat: "LEV",   sec: "Automated Film & Plate Development (P2)",
    text: "Extract vapours from the automatic processor when making larger plates or for longer periods of plate-making; wire the extraction (LEV) to the processor unit so it cannot be operated without extraction running." },
  { id: 185, group: "Lithographic Printing", cat: "LEV",   sec: "Automated Film & Plate Development (P2)",
    text: "Fit a manometer, pressure gauge or tell-tale device to the LEV extraction on the processor to confirm extraction is functioning; interlock UV lamps with the unit's fixed covers." },

  // P3 - Ink mixing and cleaning up
  { id: 186, group: "Lithographic Printing", cat: "Task",  sec: "Ink Mixing & Cleaning Up (P3)",
    text: "Use UV-curable inks and coatings that conform to the Acrylate Preference Criteria to minimise the risk of skin sensitisation." },
  { id: 187, group: "Lithographic Printing", cat: "Task",  sec: "Ink Mixing & Cleaning Up (P3)",
    text: "Avoid hand-pouring inks and reducers where reasonably practicable by providing pumped transfer systems or dispensing aids; provide easy-to-clean work surfaces with lipped edges for liquid handling." },
  { id: 188, group: "Lithographic Printing", cat: "Task",  sec: "Ink Mixing & Cleaning Up (P3)",
    text: "Handle ink containers with care and replace caps immediately after use; replace covers on ink ducts immediately to minimise solvent vapour release." },
  { id: 189, group: "Lithographic Printing", cat: "PPE",   sec: "Ink Mixing & Cleaning Up (P3)",
    text: "Provide nitrile gloves (minimum 0.4 mm thick) for ink mixing and cleaning up; follow safety data sheet advice on glove selection for specific inks and solvents." },
  { id: 190, group: "Lithographic Printing", cat: "Maint", sec: "Ink Mixing & Cleaning Up (P3)",
    text: "Check transfer hoses and connectors regularly for leaks; keep all equipment in effective working order and maintain it as advised by the supplier or installer." },

  // P4 - Printing with conventional inks
  { id: 191, group: "Lithographic Printing", cat: "Task",  sec: "Printing with Conventional Inks (P4)",
    text: "Where reasonably practicable, transfer ink via fixed pipework or use proprietary mixing systems and automatic cartridges to dispense inks to ducts, reducing manual handling." },
  { id: 192, group: "Lithographic Printing", cat: "PPE",   sec: "Printing with Conventional Inks (P4)",
    text: "Gloves are not normally needed for routine conventional ink printing operations, but must be provided for cleaning and maintenance tasks, e.g. cleaning up spills; check the safety data sheet for guidance." },

  // P5 - Manual cleaning of presses (conventional inks)
  { id: 193, group: "Lithographic Printing", cat: "Task",  sec: "Manual Press Cleaning - Conventional Inks (P5)",
    text: "Introduce automatic press cleaning systems (see P6) where reasonably practicable to reduce the risk of skin contact with cleaning solvents." },
  { id: 194, group: "Lithographic Printing", cat: "Task",  sec: "Manual Press Cleaning - Conventional Inks (P5)",
    text: "Consider substituting cleaning solvents with products of lower volatility or higher flashpoint to reduce inhalation exposure during manual press cleaning." },
  { id: 195, group: "Lithographic Printing", cat: "Task",  sec: "Manual Press Cleaning - Conventional Inks (P5)",
    text: "Use a wiping tool in place of rags or cloths to minimise manual skin contact with solvents; provide a good through draught with a fan or air mover when working in confined areas, e.g. when removing ink from cylinders or in dead spaces between machines." },
  { id: 196, group: "Lithographic Printing", cat: "Task",  sec: "Manual Press Cleaning - Conventional Inks (P5)",
    text: "If the press is fitted with LEV, turn it on for manual cleaning operations; the press should be stationary during cleaning." },
  { id: 197, group: "Lithographic Printing", cat: "PPE",   sec: "Manual Press Cleaning - Conventional Inks (P5)",
    text: "Provide nitrile gloves (minimum 0.4 mm thick) for manual press cleaning; provide eye protection, anti-static footwear, and cotton overalls; ensure workers remove and discard damaged gloves." },
  { id: 198, group: "Lithographic Printing", cat: "Clean", sec: "Manual Press Cleaning - Conventional Inks (P5)",
    text: "Store contaminated cloths, wipes and gloves in fire-resistant, closed metal containers; minimise the quantity of flammable cleaning liquids in use and dispense using a self-sealing container or proprietary dispenser." },
  { id: 199, group: "Lithographic Printing", cat: "Maint", sec: "Manual Press Cleaning - Conventional Inks (P5)",
    text: "If LEV is fitted to presses, maintain a user manual or log book setting out checking frequency, maintenance schedules and parts replacement history; where no log book exists, seek assistance from a competent person to establish required performance levels." },
  { id: 200, group: "Lithographic Printing", cat: "Maint", sec: "Manual Press Cleaning - Conventional Inks (P5)",
    text: "LEV systems fitted to presses require a statutory thorough examination and test (TExT) by a competent ventilation engineer at least once every 14 months (refer to HSE HSG258); retain records for at least five years and carry out all remedial actions arising." },

  // P6 - Automated cleaning of presses (conventional inks)
  { id: 201, group: "Lithographic Printing", cat: "Task",  sec: "Automated Press Cleaning - Conventional Inks (P6)",
    text: "Use closed pump transfer for cleaning solvents in automated blanket wash systems; check that cleaning solvents are compatible with any plastic or rubber components, e.g. flexible hoses and day tanks." },
  { id: 202, group: "Lithographic Printing", cat: "Task",  sec: "Automated Press Cleaning - Conventional Inks (P6)",
    text: "Ensure the quantity of cleaning solvents applied by the automatic blanket wash system is metered to the minimum necessary and is altered only as authorised." },
  { id: 203, group: "Lithographic Printing", cat: "PPE",   sec: "Automated Press Cleaning - Conventional Inks (P6)",
    text: "Provide nitrile gloves (minimum 0.4 mm thick) for cleaning and maintenance tasks; tell workers that gloves increase the risk of entanglement with moving rollers and cylinders - gloves must not be worn near running machinery." },

  // P7 - Printing with UV-curable inks and coatings
  { id: 204, group: "Lithographic Printing", cat: "Task",  sec: "Printing with UV-Curable Inks & Coatings (P7)",
    text: "Use UV-curable inks and coatings that conform to the Acrylate Preference Criteria; set up the machine to minimise ink misting and use LEV to remove mist, or shroud the rollers to trap mist." },
  { id: 205, group: "Lithographic Printing", cat: "Task",  sec: "Printing with UV-Curable Inks & Coatings (P7)",
    text: "Screen UV curing units with fixed or interlocked covers to avoid leaks of UV light; use LEV to remove ozone generated by UV lamps; consider water-cooled UV lamps which generate less ozone." },
  { id: 206, group: "Lithographic Printing", cat: "LEV",   sec: "Printing with UV-Curable Inks & Coatings (P7)",
    text: "Wire ozone extraction to the UV lamp power supply so extraction cannot be disabled independently; fit a manometer, pressure gauge or tell-tale device to confirm extraction is functioning." },
  { id: 207, group: "Lithographic Printing", cat: "Maint", sec: "Printing with UV-Curable Inks & Coatings (P7)",
    text: "Check airflow indicators at least once a week; ensure that screens on UV units are secure and all interlocks are in working order before commencing production." },
  { id: 208, group: "Lithographic Printing", cat: "Train", sec: "Printing with UV-Curable Inks & Coatings (P7)",
    text: "Train workers on: how the LEV system works; how to use it effectively; how to check that it is working; and what to do if something goes wrong. Extend training to cover LEV-specific topics beyond standard hazardous substances training." },

  // P8 - Manual cleaning of presses (UV-curable inks and coatings)
  { id: 209, group: "Lithographic Printing", cat: "Task",  sec: "Manual Press Cleaning - UV-Curable Inks (P8)",
    text: "Introduce automatic press cleaning systems (see P9) where reasonably practicable to reduce skin contact with solvents when cleaning presses using UV-curable inks." },
  { id: 210, group: "Lithographic Printing", cat: "Task",  sec: "Manual Press Cleaning - UV-Curable Inks (P8)",
    text: "Minimise use of highly volatile cleaners, e.g. solvents containing methyl ethyl ketone; if using more than 0.5 litres per day or for more than 30 minutes, vapour extraction is required." },
  { id: 211, group: "Lithographic Printing", cat: "PPE",   sec: "Manual Press Cleaning - UV-Curable Inks (P8)",
    text: "Provide nitrile gloves (minimum 0.4 mm thick), eye protection, anti-static footwear and an impervious apron for manual press cleaning with UV-curable inks; ensure workers remove and discard damaged gloves." },
  { id: 212, group: "Lithographic Printing", cat: "Maint", sec: "Manual Press Cleaning - UV-Curable Inks (P8)",
    text: "Ensure that screens on UV units are secure and all interlocks are in working order before commencing cleaning; check LEV systems at least weekly and carry out statutory TExT at intervals not exceeding 14 months." },

  // P9 - Automated cleaning of presses (UV-curable inks and coatings)
  { id: 213, group: "Lithographic Printing", cat: "Task",  sec: "Automated Press Cleaning - UV-Curable Inks (P9)",
    text: "Use closed pump transfer for cleaning solvents in automated UV press cleaning systems; ensure the quantity of cleaning chemicals applied by the blanket wash system is metered to the minimum necessary and altered only as authorised." },
  { id: 214, group: "Lithographic Printing", cat: "Maint", sec: "Automated Press Cleaning - UV-Curable Inks (P9)",
    text: "Ensure that screens on UV units are secure and all interlocks are in working order; carry out LEV statutory TExT at intervals not exceeding 14 months and retain records for at least five years." },

  // P10 - Printing with cold-set inks
  { id: 215, group: "Lithographic Printing", cat: "Task",  sec: "Printing with Cold-Set Inks (P10)",
    text: "Where reasonably practicable, transfer cold-set ink via fixed pipework or use proprietary mixing systems and automatic cartridges to dispense inks to ducts, reducing manual handling and vapour release." },
  { id: 216, group: "Lithographic Printing", cat: "PPE",   sec: "Printing with Cold-Set Inks (P10)",
    text: "Gloves are not normally needed for routine cold-set ink printing operations, but must be provided for cleaning and maintenance tasks, e.g. cleaning up spills; check the safety data sheet for specific PPE requirements." },

  // Common controls across the P series
  { id: 217, group: "Lithographic Printing", cat: "LEV",   sec: "General Ventilation - Lithographic Press Room",
    text: "Provide a good standard of general ventilation throughout all lithographic press rooms using powered wall- or window-mounted fans to supply fresh air at greater than five air changes per hour with a through draught." },
  { id: 218, group: "Lithographic Printing", cat: "RPE",   sec: "Respiratory Protective Equipment - Lithographic Printing",
    text: "RPE is not normally needed for routine lithographic printing operations; RPE must be provided for cleaning, maintenance activities, and spill clean-up - select RPE appropriate to the specific substance based on safety data sheet guidance." },
  { id: 219, group: "Lithographic Printing", cat: "PPE",   sec: "Skin Protection - Lithographic Printing",
    text: "Provide warm water, mild skin cleansers and soft paper or fabric towels; provide pre-work creams to facilitate post-work skin cleansing and after-work creams to replace skin oils; note that barrier creams do not provide a full barrier and are not a substitute for gloves." },
  { id: 220, group: "Lithographic Printing", cat: "PPE",   sec: "Skin Protection - Lithographic Printing",
    text: "Never allow solvents to be used for cleaning skin; if hand cleansers are needed to remove ink, ensure workers rinse them off afterwards." },
  { id: 221, group: "Lithographic Printing", cat: "Clean", sec: "Cleaning & Housekeeping - Lithographic Printing",
    text: "Clean equipment and the work area daily; clean other equipment and the workroom at least once a week; store containers in a safe place securely closed and replace lids immediately after use, even on empty containers." },
  { id: 222, group: "Lithographic Printing", cat: "Clean", sec: "Cleaning & Housekeeping - Lithographic Printing",
    text: "Deal with spills immediately by containing or absorbing liquids with granules or mats; workers handling larger spills require an impervious apron and 0.4 mm thick nitrile gloves; dispose of used granules, mats, cloths and gloves as hazardous waste." },
  { id: 223, group: "Lithographic Printing", cat: "Maint", sec: "Maintenance, Examination & Testing - Lithographic Printing",
    text: "Keep all equipment in effective working order and maintain it as advised by the supplier or installer; check control equipment for signs of damage before starting work each day; retain records of all examinations and tests for at least five years." },
  { id: 224, group: "Lithographic Printing", cat: "Health", sec: "Health Surveillance - Lithographic Printing",
    text: "Provide health surveillance for dermatitis where there is a reasonable likelihood it may occur in the workplace (refer to HSE G403); tell workers to check their skin regularly for dryness and soreness and to report any symptoms to their supervisor." },
  { id: 225, group: "Lithographic Printing", cat: "Train", sec: "Training & Supervision - Lithographic Printing",
    text: "Tell workers about the harmful nature of the substances they handle, including the signs and symptoms of dermatitis and the importance of skin care and exposure controls." },
  { id: 226, group: "Lithographic Printing", cat: "Train", sec: "Training & Supervision - Lithographic Printing",
    text: "Train workers on: working safely with hazardous substances; when and how to use controls; how to check controls are working; and what to do if something goes wrong; involve managers and supervisors in health and safety training and maintain training records." },
];
