const RECOMMENDATIONS = [

  // ═══════════════════════════════════════════════════
  // FLOUR DUST - HSE FL Series (original entries)
  // ═══════════════════════════════════════════════════

  { id: 1,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Install LEV at the source of dust generation for all flour handling tasks, including bag opening, tipping, dough mixing, moulding, dividing, bagging, and improver handling." },
  { id: 2,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "A permanent, fixed dust extraction system is the preferred option; a stand-alone mobile dust collector is acceptable only where fixed installation is not reasonably practicable." },
  { id: 3,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Enclose the process as much as possible - use see-through panels and plastic strip curtains to reduce open areas while maintaining safe access." },
  { id: 4,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Airflow velocity must be sufficient to effectively capture airborne contaminants. Adequacy will depend on hood/enclosure design, opening size, and the specific process and substance." },
  { id: 5,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Keep extraction ductwork as short and direct as possible; avoid long runs of flexible ducting." },
  { id: 6,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Position work areas away from doors, windows, and walkways to prevent draughts from disrupting LEV performance and dispersing airborne dust." },
  { id: 7,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Discharge extracted air to a safe external location, away from doors, windows, and fresh air inlets." },
  { id: 8,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Fit airflow indicators or equivalent devices on all LEV systems to allow workers to confirm the system is operating before commencing work." },
  { id: 9,  group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Fit filter blockage/failure indicator alarms to all LEV and stand-alone dust collector units." },
  { id: 10, group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Confirm LEV is switched on and functioning correctly at the start of each work period - check the gauge." },
  { id: 11, group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "For stand-alone dust collectors: the unit must not release dust on start-up and should recirculate clean air; a secondary filter meeting at least dust Type M (medium hazard) classification is required for workplace recirculation." },
  { id: 12, group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Do not allow the waste bag on stand-alone units to overfill - check gauges regularly and keep sufficient spare filters and bags on site." },
  { id: 13, group: "Flour", cat: "LEV",    sec: "LEV & Engineering Controls",
    text: "Provide a good standard of general (dilution) ventilation throughout the work area to supplement LEV." },

  { id: 14, group: "Flour", cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
    text: "Apply LEV with rim extraction at the tipping/mixing point; put a solid lid on the mixer where practicable." },
  { id: 15, group: "Flour", cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
    text: "Tip flour gently - never dump. Add ingredients gently, trickle water down the inside of the bowl, and start the mixer on slow speed." },
  { id: 16, group: "Flour", cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
    text: "When crushing empty bags, roll them up with the open end positioned within the extraction zone to capture released dust." },
  { id: 17, group: "Flour", cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
    text: "Consider providing mechanical or pneumatic bag/sack handling assistance to reduce manual handling and dust generation." },

  { id: 18, group: "Flour", cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
    text: "Use LEV cabinet extraction when weighing flour improvers." },
  { id: 19, group: "Flour", cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
    text: "Substitute high-dust improvers with low-dust alternatives wherever possible, e.g. dust-suppressed products, low-dust granules, or paste formulations." },
  { id: 20, group: "Flour", cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
    text: "Eliminate weighing entirely where practicable by using single-dose packets." },
  { id: 21, group: "Flour", cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
    text: "Open improver containers with care to minimise dust release; keep used scoops and utensils inside the extraction cabinet until cleaned." },

  { id: 22, group: "Flour", cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
    text: "Apply LEV with extraction slots at the rear of the work table; keep extraction slots free from obstructions at all times." },
  { id: 23, group: "Flour", cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
    text: "Eliminate dusting with flour wherever possible - use non-stick table surfaces or food-grade oil as a lubricant." },
  { id: 24, group: "Flour", cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
    text: "Where dusting cannot be avoided, workers should cast flour gently towards the extraction slots rather than across the open workspace." },
  { id: 25, group: "Flour", cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
    text: "Provide easy access to remove dust build-up behind extraction slots." },

  { id: 26, group: "Flour", cat: "Task",   sec: "Task-specific - Flour Bagging (FL5)",
    text: "Apply LEV enclosing the bagging point; use a filling nozzle that directs displaced air directly into the extraction system." },
  { id: 27, group: "Flour", cat: "Task",   sec: "Task-specific - Flour Bagging (FL5)",
    text: "Ensure the filling nozzle design does not spill flour when a bag is removed." },
  { id: 28, group: "Flour", cat: "Task",   sec: "Task-specific - Flour Bagging (FL5)",
    text: "Provide an extracted hopper at floor level to capture flour spills." },

  { id: 29, group: "Flour", cat: "RPE",    sec: "Respiratory Protection - Flour Dust",
    text: "Provide RPE with an assigned protection factor (APF) of at least 20 for tasks where LEV is not reasonably practicable or as a supplement to LEV during high-intensity work." },
  { id: 30, group: "Flour", cat: "PPE",    sec: "Personal Protective Equipment - Flour",
    text: "Provide and ensure workers use a dust mask or powered helmet, dust-resistant overalls and enclosed footwear." },
  { id: 31, group: "Flour", cat: "Maint",  sec: "Maintenance & Testing - Flour Dust Control",
    text: "Carry out statutory thorough examination and test (TExT) of LEV systems at least once every 14 months by a competent ventilation engineer and retain records for at least five years." },
  { id: 32, group: "Flour", cat: "Health", sec: "Health Surveillance - Flour Dust",
    text: "Provide health surveillance for occupational asthma where there is a reasonable likelihood it may occur in the workplace." },
  { id: 33, group: "Flour", cat: "Train",  sec: "Training - Flour Dust Control",
    text: "Train workers on: the health hazards from flour dust; how to use LEV and RPE effectively; how to check controls are working; and what to do if something goes wrong." },

  // ═══════════════════════════════════════════════════
  // LITHOGRAPHIC PRINTING - HSE P Series (original entries 34-67)
  // ═══════════════════════════════════════════════════

  { id: 34, group: "Lithographic Printing", cat: "Task",  sec: "Manual Press Cleaning - Conventional Inks (P1)",
    text: "Minimise use of volatile cleaning solvents; use low-volatility cleaners where possible, e.g. esters rather than ketones or aromatic hydrocarbons." },
  { id: 35, group: "Lithographic Printing", cat: "Task",  sec: "Manual Press Cleaning - Conventional Inks (P1)",
    text: "Use closed containers for solvent storage and transfer; minimise the time containers are open." },
  { id: 36, group: "Lithographic Printing", cat: "PPE",   sec: "Manual Press Cleaning - Conventional Inks (P1)",
    text: "Provide nitrile gloves (minimum 0.4 mm thick) for all cleaning and maintenance tasks; ensure workers remove and discard damaged gloves." },
  { id: 37, group: "Lithographic Printing", cat: "LEV",   sec: "Manual Press Cleaning - Conventional Inks (P1)",
    text: "Provide vapour extraction for cleaning and maintenance activities where more than 0.5 litres per day of volatile solvents are used or for more than 30 minutes duration." },

  { id: 38, group: "Lithographic Printing", cat: "Task",  sec: "Printing - Conventional Inks (P2)",
    text: "Minimise ink misting by keeping ink levels appropriate and using correct press temperature and humidity settings." },
  { id: 39, group: "Lithographic Printing", cat: "LEV",   sec: "Printing - Conventional Inks (P2)",
    text: "Use LEV to remove ink mist from the press; position the capture hood close to the source of mist generation." },

  { id: 40, group: "Lithographic Printing", cat: "Task",  sec: "Roller and Blanket Cleaning (P3)",
    text: "Use closed pump transfer for cleaning solvents; avoid manual handling and manual application of cleaning chemicals." },
  { id: 41, group: "Lithographic Printing", cat: "Task",  sec: "Roller and Blanket Cleaning (P3)",
    text: "Ensure the quantity of cleaning solvents applied by automatic systems is metered to the minimum necessary." },

  { id: 42, group: "Lithographic Printing", cat: "Task",  sec: "Automated Press Cleaning - Conventional Inks (P6)",
    text: "Use closed pump transfer for cleaning solvents in automated blanket wash systems; check that cleaning solvents are compatible with any plastic or rubber components, e.g. flexible hoses and day tanks." },
  { id: 43, group: "Lithographic Printing", cat: "Task",  sec: "Automated Press Cleaning - Conventional Inks (P6)",
    text: "Ensure the quantity of cleaning solvents applied by the automatic blanket wash system is metered to the minimum necessary and is altered only as authorised." },
  { id: 44, group: "Lithographic Printing", cat: "PPE",   sec: "Automated Press Cleaning - Conventional Inks (P6)",
    text: "Provide nitrile gloves (minimum 0.4 mm thick) for cleaning and maintenance tasks; tell workers that gloves increase the risk of entanglement with moving rollers and cylinders - gloves must not be worn near running machinery." },

  { id: 45, group: "Lithographic Printing", cat: "Task",  sec: "Printing with UV-Curable Inks & Coatings (P7)",
    text: "Use UV-curable inks and coatings that conform to the Acrylate Preference Criteria; set up the machine to minimise ink misting and use LEV to remove mist, or shroud the rollers to trap mist." },
  { id: 46, group: "Lithographic Printing", cat: "Task",  sec: "Printing with UV-Curable Inks & Coatings (P7)",
    text: "Screen UV curing units with fixed or interlocked covers to avoid leaks of UV light; use LEV to remove ozone generated by UV lamps; consider water-cooled UV lamps which generate less ozone." },
  { id: 47, group: "Lithographic Printing", cat: "LEV",   sec: "Printing with UV-Curable Inks & Coatings (P7)",
    text: "Wire ozone extraction to the UV lamp power supply so extraction cannot be disabled independently; fit a manometer, pressure gauge or tell-tale device to confirm extraction is functioning." },
  { id: 48, group: "Lithographic Printing", cat: "Maint", sec: "Printing with UV-Curable Inks & Coatings (P7)",
    text: "Check airflow indicators at least once a week; ensure that screens on UV units are secure and all interlocks are in working order before commencing production." },
  { id: 49, group: "Lithographic Printing", cat: "Train", sec: "Printing with UV-Curable Inks & Coatings (P7)",
    text: "Train workers on: how the LEV system works; how to use it effectively; how to check that it is working; and what to do if something goes wrong. Extend training to cover LEV-specific topics beyond standard hazardous substances training." },

  { id: 50, group: "Lithographic Printing", cat: "Task",  sec: "Manual Press Cleaning - UV-Curable Inks (P8)",
    text: "Introduce automatic press cleaning systems (see P9) where reasonably practicable to reduce skin contact with solvents when cleaning presses using UV-curable inks." },
  { id: 51, group: "Lithographic Printing", cat: "Task",  sec: "Manual Press Cleaning - UV-Curable Inks (P8)",
    text: "Minimise use of highly volatile cleaners, e.g. solvents containing methyl ethyl ketone; if using more than 0.5 litres per day or for more than 30 minutes, vapour extraction is required." },
  { id: 52, group: "Lithographic Printing", cat: "PPE",   sec: "Manual Press Cleaning - UV-Curable Inks (P8)",
    text: "Provide nitrile gloves (minimum 0.4 mm thick), eye protection, anti-static footwear and an impervious apron for manual press cleaning with UV-curable inks; ensure workers remove and discard damaged gloves." },
  { id: 53, group: "Lithographic Printing", cat: "Maint", sec: "Manual Press Cleaning - UV-Curable Inks (P8)",
    text: "Ensure that screens on UV units are secure and all interlocks are in working order before commencing cleaning; check LEV systems at least weekly and carry out statutory TExT at intervals not exceeding 14 months." },

  { id: 54, group: "Lithographic Printing", cat: "Task",  sec: "Automated Press Cleaning - UV-Curable Inks (P9)",
    text: "Use closed pump transfer for cleaning solvents in automated UV press cleaning systems; ensure the quantity of cleaning chemicals applied by the blanket wash system is metered to the minimum necessary and altered only as authorised." },
  { id: 55, group: "Lithographic Printing", cat: "Maint", sec: "Automated Press Cleaning - UV-Curable Inks (P9)",
    text: "Ensure that screens on UV units are secure and all interlocks are in working order; carry out LEV statutory TExT at intervals not exceeding 14 months and retain records for at least five years." },

  { id: 56, group: "Lithographic Printing", cat: "Task",  sec: "Printing with Cold-Set Inks (P10)",
    text: "Where reasonably practicable, transfer cold-set ink via fixed pipework or use proprietary mixing systems and automatic cartridges to dispense inks to ducts, reducing manual handling and vapour release." },
  { id: 57, group: "Lithographic Printing", cat: "PPE",   sec: "Printing with Cold-Set Inks (P10)",
    text: "Gloves are not normally needed for routine cold-set ink printing operations, but must be provided for cleaning and maintenance tasks, e.g. cleaning up spills; check the safety data sheet for specific PPE requirements." },

  { id: 58, group: "Lithographic Printing", cat: "LEV",   sec: "General Ventilation - Lithographic Press Room",
    text: "Provide a good standard of general ventilation throughout all lithographic press rooms using powered wall- or window-mounted fans to supply fresh air at greater than five air changes per hour with a through draught." },
  { id: 59, group: "Lithographic Printing", cat: "RPE",   sec: "Respiratory Protective Equipment - Lithographic Printing",
    text: "RPE is not normally needed for routine lithographic printing operations; RPE must be provided for cleaning, maintenance activities, and spill clean-up - select RPE appropriate to the specific substance based on safety data sheet guidance." },
  { id: 60, group: "Lithographic Printing", cat: "PPE",   sec: "Skin Protection - Lithographic Printing",
    text: "Provide warm water, mild skin cleansers and soft paper or fabric towels; provide pre-work creams to facilitate post-work skin cleansing and after-work creams to replace skin oils; note that barrier creams do not provide a full barrier and are not a substitute for gloves." },
  { id: 61, group: "Lithographic Printing", cat: "PPE",   sec: "Skin Protection - Lithographic Printing",
    text: "Never allow solvents to be used for cleaning skin; if hand cleansers are needed to remove ink, ensure workers rinse them off afterwards." },
  { id: 62, group: "Lithographic Printing", cat: "Clean", sec: "Cleaning & Housekeeping - Lithographic Printing",
    text: "Clean equipment and the work area daily; clean other equipment and the workroom at least once a week; store containers in a safe place securely closed and replace lids immediately after use, even on empty containers." },
  { id: 63, group: "Lithographic Printing", cat: "Clean", sec: "Cleaning & Housekeeping - Lithographic Printing",
    text: "Deal with spills immediately by containing or absorbing liquids with granules or mats; workers handling larger spills require an impervious apron and 0.4 mm thick nitrile gloves; dispose of used granules, mats, cloths and gloves as hazardous waste." },
  { id: 64, group: "Lithographic Printing", cat: "Maint", sec: "Maintenance, Examination & Testing - Lithographic Printing",
    text: "Keep all equipment in effective working order and maintain it as advised by the supplier or installer; check control equipment for signs of damage before starting work each day; retain records of all examinations and tests for at least five years." },
  { id: 65, group: "Lithographic Printing", cat: "Health", sec: "Health Surveillance - Lithographic Printing",
    text: "Provide health surveillance for dermatitis where there is a reasonable likelihood it may occur in the workplace (refer to HSE G403); tell workers to check their skin regularly for dryness and soreness and to report any symptoms to their supervisor." },
  { id: 66, group: "Lithographic Printing", cat: "Train", sec: "Training & Supervision - Lithographic Printing",
    text: "Tell workers about the harmful nature of the substances they handle, including the signs and symptoms of dermatitis and the importance of skin care and exposure controls." },
  { id: 67, group: "Lithographic Printing", cat: "Train", sec: "Training & Supervision - Lithographic Printing",
    text: "Train workers on: working safely with hazardous substances; when and how to use controls; how to check controls are working; and what to do if something goes wrong; involve managers and supervisors in health and safety training and maintain training records." },

  // ═══════════════════════════════════════════════════
  // WELDING - HSE WL Series
  // ═══════════════════════════════════════════════════

  // WL2 - Welding in confined/limited/restricted spaces
  { id: 227, group: "Welding", cat: "Task", sec: "Task-specific - Confined/Limited/Restricted Spaces (WL2)",
    text: "Ensure good air movement and mixing by a suitable means of forced ventilation in confined/limited/restricted spaces; develop a safe system of work under the Safe Work in Confined Spaces Regulations 1997 and obtain a permit-to-work." },
  { id: 228, group: "Welding", cat: "Task", sec: "Task-specific - Confined/Limited/Restricted Spaces (WL2)",
    text: "Check the concentration of oxygen in the air before entry and monitor continuously during the procedure; never use fuelled engines or combustion equipment in confined spaces as carbon monoxide gas can cause asphyxia and death." },
  { id: 229, group: "Welding", cat: "Task", sec: "Task-specific - Confined/Limited/Restricted Spaces (WL2)",
    text: "Have a competent person perform toxic and flammable gas/vapour tests; provide personal gas monitors for the gases that may be encountered in the confined space." },
  { id: 230, group: "Welding", cat: "Task", sec: "Task-specific - Confined/Limited/Restricted Spaces (WL2)",
    text: "Isolate mechanical and electrical equipment that could cause harm if turned on; ensure safe access and egress from the confined space, access routes and hatches are large enough, and rescue harnesses are suitable." },
  { id: 231, group: "Welding", cat: "Task", sec: "Task-specific - Confined/Limited/Restricted Spaces (WL2)",
    text: "Use non-sparking tools or flameproof lighting for the task; ensure that people inside the space can communicate with those outside and that workers are checked in and out where multiple entry occurs." },
  { id: 232, group: "Welding", cat: "RPE",  sec: "Task-specific - Confined/Limited/Restricted Spaces (WL2)",
    text: "Provide air-fed 'CE'-marked RPE with an Assigned Protection Factor (APF) of at least 40, or cylinder breathing apparatus (BA) if oxygen levels could be depleted; wearers must be medically fit to wear BA and air supplied must meet the latest British Standard." },
  { id: 233, group: "Welding", cat: "Task", sec: "Task-specific - Confined/Limited/Restricted Spaces (WL2)",
    text: "Plan emergency rescue in advance with a specific plan identifying the confined space, risks, number of people at work, and likely nature of emergency rescue; define means for communication between workers and rescuers, rescuers' capabilities and training, rescue equipment needs, and any emergency shut-down of plant." },

  // WL3 - Welding fume control
  { id: 234, group: "Welding", cat: "Task", sec: "Welding Fume Control - Process Design (WL3)",
    text: "Design the job to use less welding by considering cold joining techniques, mechanical fasteners, thinner gauge metal or new adhesive technologies." },
  { id: 235, group: "Welding", cat: "Task", sec: "Welding Fume Control - Process Design (WL3)",
    text: "Remove grease and all surface coatings first before welding; paint and resin coatings may release toxic components when heated." },
  { id: 236, group: "Welding", cat: "Task", sec: "Welding Fume Control - Process Design (WL3)",
    text: "Position the workpiece and LEV hood to reduce the worker being exposed to the rising fume; when welding outdoors in the open air, LEV is usually not a practical option for fume capture, use RPE as a suitable alternative choice of control." },
  { id: 237, group: "Welding", cat: "LEV",  sec: "Welding Fume Control - LEV Design (WL3)",
    text: "Select the most appropriate extraction design for your welding processes; ensure all elements are well designed and matched to the requirements of your process, as the design of the hood is particularly important as it determines how well the system captures the fume." },
  { id: 238, group: "Welding", cat: "LEV",  sec: "Welding Fume Control - LEV Design (WL3)",
    text: "Use a reputable supplier of LEV systems; ventilation engineers you invite to bid for a contract should be able to show their experience of this type of work." },
  { id: 239, group: "Welding", cat: "LEV",  sec: "Welding Fume Control - LEV Monitoring (WL3)",
    text: "Provide an easy way of checking the LEV is working, eg. airflow indicator; ensure extracted air is discharged ideally outside the building to a safe place away from doors, windows and air inlets." },
  { id: 240, group: "Welding", cat: "LEV",  sec: "Welding Fume Control - Filters (WL3)",
    text: "Provide a suitable filter for welding fume in the extraction unit and ensure that it is regularly inspected and replaced when necessary; fit an indicator or alarm to show if filters have blocked or failed." },
  { id: 241, group: "Welding", cat: "Task", sec: "Welding Fume Control - Small/Medium Workpieces (WL3)",
    text: "Use an extracted bench or extracted booth which draws fume away from the welder towards the air inlet at the back, when welding small to medium sized articles; with this design of LEV, the extraction hood does not need to be repositioned during welding to maintain adequate fume capture." },
  { id: 242, group: "Welding", cat: "Task", sec: "Welding Fume Control - Small/Medium Workpieces (WL3)",
    text: "Ensure the fume is drawn away from the welder through the series of extraction holes or slots in the bench or booth; enclose as much of the bench as practicable to prevent cross-draughts and improve fume capture effectiveness." },
  { id: 243, group: "Welding", cat: "Task", sec: "Welding Fume Control - Small/Medium Workpieces (WL3)",
    text: "Keep the work surface of the extracted bench free from clutter so as not to restrict the air movement; position the workpiece correctly on the bench to ensure effective capture of fume." },
  { id: 244, group: "Welding", cat: "Task", sec: "Welding Fume Control - Small/Medium Workpieces (WL3)",
    text: "Ensure that the workpiece (or the area to be welded) is entirely within the booth; use of a turntable or bespoke jig allows positioning to ensure fume is taken away from the welder." },
  { id: 245, group: "Welding", cat: "Task", sec: "Welding Fume Control - Large Workpieces (WL3)",
    text: "Use on-torch extraction as this is the most effective fume control for MIG welding when it is set up and used correctly; for other types of welding where on-torch extraction cannot be used, use LEV with a movable fume capture hood." },
  { id: 246, group: "Welding", cat: "Task", sec: "Welding Fume Control - Large Workpieces (WL3)",
    text: "Ensure the correct set-up so it can be used without compromising weld integrity; on-torch extraction is effective because the extraction is integrated with the welding gun, moves with the weld, is very close to the source at all times, and does not rely on the welder to reposition the extraction." },
  { id: 247, group: "Welding", cat: "Task", sec: "Welding Fume Control - Large Workpieces (WL3)",
    text: "Be aware that on-torch extraction is not always practical when welding is carried out while working at height; research has shown that on-torch is more effective when groove welding on a flat surface (eg. downhand, horizontal or vertical) than when fillet welding or groove welding in the overhead position." },
  { id: 248, group: "Welding", cat: "Task", sec: "Welding Fume Control - Large Workpieces (WL3)",
    text: "Use a movable fume capture hood on a flexible extraction arm for large to extra-large workpieces when other, more effective LEV designs are not practical; select an appropriate design of hood to maximise the fume capture from your welding process by considering its shape, size or hood diameter and whether flanged capture hoods can be used." },
  { id: 249, group: "Welding", cat: "Task", sec: "Welding Fume Control - Large Workpieces (WL3)",
    text: "Position movable hoods within one hood diameter of the welding point to collect fume effectively, otherwise they will not capture the welding fume; it can be helpful to mark out the capture zone of a movable hood." },
  { id: 250, group: "Welding", cat: "Task", sec: "Welding Fume Control - Large Workpieces (WL3)",
    text: "Ensure the careful positioning and repositioning of the capture hood as often as necessary to maintain the optimal fume capture; ensure ducting is free from acute bends and kinks, holes and cracks and avoid long sections of flexible ducting." },
  { id: 251, group: "Welding", cat: "RPE",  sec: "Welding Fume Control - RPE Selection (WL3)",
    text: "Provide RPE with an assigned protection factor (APF) of at least 20; fit testing is required for RPE with a tight-fitting face seal (refer to HSG53 Respiratory protective equipment at work - A practical guide)." },
  { id: 252, group: "Welding", cat: "RPE",  sec: "Welding Fume Control - RPE Selection (WL3)",
    text: "Workers wearing tight-fitting RPE must be clean-shaven, trained how to fit it properly and how to look after it; tell workers to discard disposable RPE at the end of the shift, or sooner if their RPE becomes blocked with fume or dust." },
  { id: 253, group: "Welding", cat: "RPE",  sec: "Welding Fume Control - RPE Maintenance (WL3)",
    text: "Change the filters on respirators in accordance with manufacturers' recommendations and if: the shelf-life expiry date has passed; they are damaged or visibly contaminated; they become harder to breathe through." },
  { id: 254, group: "Welding", cat: "RPE",  sec: "Welding Fume Control - RPE Maintenance (WL3)",
    text: "Examine and test non-disposable RPE thoroughly at least once every month and record this; tell workers to check RPE is working properly before every use." },
  { id: 255, group: "Welding", cat: "RPE",  sec: "Welding Fume Control - Powered RPE (WL3)",
    text: "Use a powered respirator when a welder is required to carry out welding for more than 1 hour per day; powered respirators with an integral welding visor protect the skin and eyes from UV and an additional clear viewing window." },
  { id: 256, group: "Welding", cat: "RPE",  sec: "Welding Fume Control - Powered RPE (WL3)",
    text: "Powered respirators used for welding should have a particulate filter; TH2 filters have an assigned protection factor of 20, TH3 filters have a higher protection factor of 40." },
  { id: 257, group: "Welding", cat: "LEV",  sec: "Welding Fume Control - General Ventilation (WL3)",
    text: "Provide effective general ventilation to minimise fume build-up over the shift; in most welding workshops mechanical general ventilation will be required because natural ventilation from open doors and windows is not sufficient to disperse the fume generated from the work tasks." },
  { id: 258, group: "Welding", cat: "LEV",  sec: "Welding Fume Control - General Ventilation (WL3)",
    text: "For processes which produce little fume in a substantially sized work area, effective general ventilation may adequately control exposure; examples include low-intensity resistance spot welding and low-intensity TIG welding." },
  { id: 259, group: "Welding", cat: "Maint", sec: "Welding Fume Control - LEV Commissioning (WL3)",
    text: "When a LEV system has been purchased ensure it is commissioned; commissioning provides the design specification, the checks that were carried out to ensure fume control, and the data needed for its technical performance." },
  { id: 260, group: "Welding", cat: "Maint", sec: "Welding Fume Control - LEV Maintenance (WL3)",
    text: "Keep all equipment used for the task in effective working order; maintain it as advised by the supplier or installer; check for signs of damage to LEV equipment before starting work." },
  { id: 261, group: "Welding", cat: "Maint", sec: "Welding Fume Control - LEV Maintenance (WL3)",
    text: "Your LEV supplier should have provided a user manual that includes how to use the system, how to maintain it, the spares available and a list of things that can go wrong; you should have an LEV system logbook that contains schedules and records of regular checking, maintenance and repair." },
  { id: 262, group: "Welding", cat: "Maint", sec: "Welding Fume Control - LEV Testing (WL3)",
    text: "LEV systems require a statutory 'thorough examination and test' (TExT) under COSHH Regulation 9; get a competent ventilation engineer to perform the TExT at least once every 14 months." },
  { id: 263, group: "Welding", cat: "Maint", sec: "Welding Fume Control - LEV Testing (WL3)",
    text: "Carry out all actions arising from the TExT; keep an employer record for at least 5 years of each TExT including target extraction rates showing the LEV is performing as originally intended." },
  { id: 264, group: "Welding", cat: "Maint", sec: "Welding Fume Control - LEV Effectiveness (WL3)",
    text: "Carry out weekly visual checks that the LEV is working and keep a record; several measures are available to check effectiveness of controls, ranging from simple qualitative (use of dust lamp) to complex quantitative techniques (eg. air sampling)." },
  { id: 265, group: "Welding", cat: "Health", sec: "Welding Fume Control - Health Surveillance (WL3)",
    text: "Provide health surveillance for asthma where there is a reasonable likelihood that asthma may occur in your workplace, for example when regularly welding with metals which will generate respiratory sensitisers in the welding fume (refer to HSE G402)." },
  { id: 266, group: "Welding", cat: "Train", sec: "Welding Fume Control - Training (WL3)",
    text: "Provide supervision - ensure that safe work procedures are followed; tell workers about the health hazards from welding fume; explain that working in the right way and using the controls correctly is important for exposure control." },
  { id: 267, group: "Welding", cat: "Train", sec: "Welding Fume Control - Training (WL3)",
    text: "Provide workers with training on: following safe working procedures; when and how to use controls; how to check the LEV is working effectively; how the LEV system works; how to use the LEV to get the best out of it; how to position themselves and the workpiece." },

  // WL14 - Manual gas and oxy-gas cutting
  { id: 268, group: "Welding", cat: "Task", sec: "Task-specific - Manual Gas & Oxy-Gas Cutting (WL14)",
    text: "Consider an automated system for tasks of long duration; provide a good standard of general ventilation; arrange work to reduce the worker's exposure to fume, eg keep the welder's head out of the fume." },
  { id: 269, group: "Welding", cat: "Task", sec: "Task-specific - Manual Gas & Oxy-Gas Cutting (WL14)",
    text: "Remove grease and all surface coatings first; purge the gas hoses to ensure no other gas is present before lighting the flame." },
  { id: 270, group: "Welding", cat: "Task", sec: "Task-specific - Manual Gas & Oxy-Gas Cutting (WL14)",
    text: "Ensure to use a flashback arrestor on both cylinders for oxy-acetylene cutting; check that gas cylinder regulators are connected correctly and are not leaking gas, where applicable." },
  { id: 271, group: "Welding", cat: "Task", sec: "Task-specific - Manual Gas & Oxy-Gas Cutting (WL14)",
    text: "Where possible, site the work area away from doors, windows and walkways, to stop the spread of the airborne contaminant." },
  { id: 272, group: "Welding", cat: "RPE",  sec: "Task-specific - Manual Gas & Oxy-Gas Cutting (WL14)",
    text: "Provide RPE with an assigned protection factor (APF) of at least 20; the type of cutting to be undertaken will determine the APF required." },
  { id: 273, group: "Welding", cat: "RPE",  sec: "Task-specific - Manual Gas & Oxy-Gas Cutting (WL14)",
    text: "Fit testing is required for RPE with a tight-fitting face seal; workers wearing tight-fitting RPE must be clean-shaven and trained how to fit it properly and how to look after it." },
  { id: 274, group: "Welding", cat: "RPE",  sec: "Task-specific - Manual Gas & Oxy-Gas Cutting (WL14)",
    text: "Tell workers to discard disposable RPE at the end of the shift or sooner if blocked with dust; change filters in accordance with manufacturers' recommendations." },
  { id: 275, group: "Welding", cat: "RPE",  sec: "Task-specific - Manual Gas & Oxy-Gas Cutting (WL14)",
    text: "Examine and test non-disposable RPE thoroughly at least once every month and record this; tell workers to check RPE before every use and record this." },
  { id: 276, group: "Welding", cat: "RPE",  sec: "Task-specific - Manual Gas & Oxy-Gas Cutting (WL14)",
    text: "If a wearer cannot achieve the necessary fit in a test, use another type of RPE; a powered respirator or supplied air BA with welding visor is more comfortable to wear for longer periods of time." },
  { id: 277, group: "Welding", cat: "PPE",  sec: "Task-specific - Manual Gas & Oxy-Gas Cutting (WL14)",
    text: "Keep RPE clean and store it in a clean place; make suitable arrangements for maintenance, storage and replacement." },
  { id: 278, group: "Welding", cat: "Clean", sec: "Task-specific - Manual Gas & Oxy-Gas Cutting (WL14)",
    text: "Keep the work area clean and free of combustible materials." },
  { id: 279, group: "Welding", cat: "Exp",  sec: "Task-specific - Manual Gas & Oxy-Gas Cutting (WL14)",
    text: "Consider exposure monitoring as a check on the effectiveness of control measures in place when cutting: stainless steels; non-ferrous alloys; painted or coated metals (refer to HSE G409 Exposure measurement: Air sampling)." },
  { id: 280, group: "Welding", cat: "Health", sec: "Task-specific - Manual Gas & Oxy-Gas Cutting (WL14)",
    text: "Provide health surveillance for asthma where there is a reasonable likelihood that asthma may occur in your workplace (refer to HSE G402)." },

  // WL15 - Plasma arc cutting fixed equipment
  { id: 281, group: "Welding", cat: "Task", sec: "Task-specific - Plasma Arc Cutting Fixed Equipment (WL15)",
    text: "Use a mechanised plasma cutter within a water bath to enable the cutting to take place submerged under water; local exhaust ventilation (LEV) may be required around the torch above the water level." },
  { id: 282, group: "Welding", cat: "Task", sec: "Task-specific - Plasma Arc Cutting Fixed Equipment (WL15)",
    text: "Ensure there are no hazardous fumes generated from the addition of corrosion inhibitors into the baths; regularly clean out water baths, as the cutting of aluminium alloys can lead to the deposition of metal and accumulation of dross which will generate hydrogen." },
  { id: 283, group: "Welding", cat: "Task", sec: "Task-specific - Plasma Arc Cutting Fixed Equipment (WL15)",
    text: "Remove grease and all surface coatings first; use in-air plasma cutters with an under-table extraction system to ensure workers are protected from the arc generated." },
  { id: 284, group: "Welding", cat: "Task", sec: "Task-specific - Plasma Arc Cutting Fixed Equipment (WL15)",
    text: "Where possible, site the work area away from doors, windows and walkways, to stop draughts interfering with the LEV and spreading the airborne contaminant." },
  { id: 285, group: "Welding", cat: "Maint", sec: "Task-specific - Plasma Arc Cutting Fixed Equipment (WL15)",
    text: "LEV systems require a statutory 'thorough examination and test' (TExT); get a competent person to perform at least once every 14 months." },
  { id: 286, group: "Welding", cat: "Maint", sec: "Task-specific - Plasma Arc Cutting Fixed Equipment (WL15)",
    text: "Keep an employer record for at least 5 years of TExT information such as target extraction rates which show the LEV is performing as originally intended." },

  // WL16 - Arc-air gouging
  { id: 287, group: "Welding", cat: "Task", sec: "Task-specific - Arc-Air Gouging (WL16)",
    text: "Isolate this task from the workforce by carrying out the work in a booth or segregated area with local exhaust ventilation (LEV); provide an enclosed extracted booth and RPE." },
  { id: 288, group: "Welding", cat: "LEV",  sec: "Task-specific - Arc-Air Gouging (WL16)",
    text: "Provide an easy way of checking the booth extraction is working, eg airflow indicator or equivalent; always confirm that the extraction is turned on and working at the start of work." },
  { id: 289, group: "Welding", cat: "Task", sec: "Task-specific - Arc-Air Gouging (WL16)",
    text: "Discharge extracted air to a safe place away from doors, windows and air inlets; arrange work to reduce the worker's exposure to the fume, eg welder's head is out of the fume." },
  { id: 290, group: "Welding", cat: "RPE",  sec: "Task-specific - Arc-Air Gouging (WL16)",
    text: "Provide a powered respirator with welding helmet, with a protection factor of 40 for tasks lasting less than 30 minutes per shift; provide airline breathing apparatus (BA) for tasks lasting more than 30 minutes per shift." },
  { id: 291, group: "Welding", cat: "RPE",  sec: "Task-specific - Arc-Air Gouging (WL16)",
    text: "Wearers must be medically fit to wear BA; air supplied to BA should meet minimum quality requirements, in line with the latest British Standard." },
  { id: 292, group: "Welding", cat: "RPE",  sec: "Task-specific - Arc-Air Gouging (WL16)",
    text: "Examine and test non-disposable RPE thoroughly at least once every three months and record this; tell workers to check RPE is working properly before every use and record this." },
  { id: 293, group: "Welding", cat: "RPE",  sec: "Task-specific - Arc-Air Gouging (WL16)",
    text: "Keep RPE clean and store it in a clean place; make suitable arrangements for maintenance, storage and replacement of RPE." },
  { id: 294, group: "Welding", cat: "Exp",  sec: "Task-specific - Arc-Air Gouging (WL16)",
    text: "Exposure monitoring should be considered as a check on the effectiveness of control measures in place when welding: stainless steels; non-ferrous alloys; painted or coated metals (refer to HSE G409)." },
  { id: 295, group: "Welding", cat: "Train", sec: "Task-specific - Arc-Air Gouging (WL16)",
    text: "Provide supervision – ensure that safe work procedures are followed; tell workers about the health hazards from welding fume; provide workers with training on: following safe working procedures; when and how to use controls; how to check they are working; how the LEV system works." },

  // WL18 - Pressure blasting small items
  { id: 296, group: "Welding", cat: "Task", sec: "Task-specific - Pressure Blasting Small Items (WL18)",
    text: "Use a fully enclosed cabinet or booth for blasting, kept under negative pressure; consider wet blasting or high-pressure water jetting instead of dry abrasive blasting." },
  { id: 297, group: "Welding", cat: "Task", sec: "Task-specific - Pressure Blasting Small Items (WL18)",
    text: "Fit a pressure gauge, interlocked with the power supply; you need a high standard of filtration for the air discharged from the booth." },
  { id: 298, group: "Welding", cat: "Task", sec: "Task-specific - Pressure Blasting Small Items (WL18)",
    text: "Discharge extracted air to a safe place away from doors, windows and air inlets; run the booth for two minutes after blasting has ceased to clear the air." },
  { id: 299, group: "Welding", cat: "Maint", sec: "Task-specific - Pressure Blasting Small Items (WL18)",
    text: "For local exhaust ventilation (LEV), a user manual or log book is helpful in setting out the frequency of checking, maintenance or parts replacement; if none exists, get help from a competent person." },
  { id: 300, group: "Welding", cat: "Maint", sec: "Task-specific - Pressure Blasting Small Items (WL18)",
    text: "LEV systems require a statutory 'thorough examination and test' (TExT); get a competent person to perform at least once every 14 months; keep an employer record for at least 5 years of TExT information such as target extraction rates." },
  { id: 301, group: "Welding", cat: "Clean", sec: "Task-specific - Pressure Blasting Small Items (WL18)",
    text: "Keep the work area clean and free of combustible materials." },

  // WL19 - Pressure blasting medium items (intentionally omitted - not in uploaded PDFs)

  // WL20 - Pressure blasting large items (intentionally omitted - not in uploaded PDFs)

  // WL21 - Weld cleaning with pickling paste
  { id: 302, group: "Welding", cat: "Task", sec: "Task-specific - Weld Cleaning Pickling Paste (WL21)",
    text: "Consider using alternative post-welding cleaning measures, eg mechanical or electrochemical; consider using a paste with a lower acid concentration or a higher viscosity." },
  { id: 303, group: "Welding", cat: "Task", sec: "Task-specific - Weld Cleaning Pickling Paste (WL21)",
    text: "Provide a good standard of general ventilation; buy pastes in the right-sized containers, don't store far more than you need and avoid decanting." },
  { id: 304, group: "Welding", cat: "Task", sec: "Task-specific - Weld Cleaning Pickling Paste (WL21)",
    text: "Remove surplus paste with a damp cloth and discard immediately to contaminated waste; avoid using pastes in confined spaces." },
  { id: 305, group: "Welding", cat: "Task", sec: "Task-specific - Weld Cleaning Pickling Paste (WL21)",
    text: "Avoid paste spraying - if you must do this, seek specialist advice; apply by brush rather than by roller." },
  { id: 306, group: "Welding", cat: "Task", sec: "Task-specific - Weld Cleaning Pickling Paste (WL21)",
    text: "Ensure that first aid provisions are adequate; stock calcium gluconate gel and keep it handy for hydrofluoric acid (HF) burns." },
  { id: 307, group: "Welding", cat: "Task", sec: "Task-specific - Weld Cleaning Pickling Paste (WL21)",
    text: "Wash contaminated skin with large amounts of running water; in the case of HF burns, apply gel to the affected area and continue massaging this into the skin until the patient reaches hospital and gets medical attention (refer to HSE INDG307)." },
  { id: 308, group: "Welding", cat: "PPE",  sec: "Task-specific - Weld Cleaning Pickling Paste (WL21)",
    text: "Provide suitable chemical protective gloves, eg nitrile (and new gloves when these are damaged), eye protection, overalls and footwear." },
  { id: 309, group: "Welding", cat: "PPE",  sec: "Task-specific - Weld Cleaning Pickling Paste (WL21)",
    text: "Make suitable arrangements for maintenance, storage and replacement of PPE; use a contract laundry or suitable equivalent to wash work clothing, don't allow workers to do this at home." },
  { id: 310, group: "Welding", cat: "Clean", sec: "Task-specific - Weld Cleaning Pickling Paste (WL21)",
    text: "Keep the work area clean and free of combustible materials; store and dispose of hazardous waste safely; deal with spills immediately - use suitable protective gloves." },
  { id: 311, group: "Welding", cat: "Health", sec: "Task-specific - Weld Cleaning Pickling Paste (WL21)",
    text: "Provide health surveillance for dermatitis where there is a reasonable likelihood that dermatitis may occur in your workplace (refer to HSE G403)." },
  { id: 312, group: "Welding", cat: "Train", sec: "Task-specific - Weld Cleaning Pickling Paste (WL21)",
    text: "Provide supervision – ensure that safe work procedures are followed; tell workers that paste can cause serious skin and eye damage and instruct them how to get first aid after any skin or eye contact." },
  { id: 313, group: "Welding", cat: "Train", sec: "Task-specific - Weld Cleaning Pickling Paste (WL21)",
    text: "Working in the right way and using the controls correctly is important for exposure control; training could include toolbox talks on: following safe working procedures; how to use equipment correctly; what to do if they get pickling paste on their skin or eyes." },
  { id: 314, group: "Welding", cat: "Train", sec: "Task-specific - Weld Cleaning Pickling Paste (WL21)",
    text: "Consider keeping training records; have a procedure to check that control measures are in place and being followed; involve managers and supervisors in health and safety training (refer to HSE WL0)." },

];
